Provide SUPERADMIN with all privileges of ADMIN
PalisadoesFoundation/talawa-api pull request #1139
Opened 2023-03-08 07:56 UTC by beingnoble03

**What kind of change does this PR introduce?**
Provides SUPERADMIN with all privileges of ADMIN 

**Issue Number:**

Fixes #1124 

**Did you add tests for your changes?**
Yes

**Snapshots/Videos:**

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**
No.

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**
Yes

2023-03-09 19:19 UTC, noman2002 requested changes
Fix the conflicting files.

2023-03-10 17:41 UTC, beingnoble03 commented
@noman2002 done. Ptal, thanks!

2023-03-10 17:48 UTC, beingnoble03 commented
@noman2002 done. Ptal, thanks!

2023-03-11 02:27 UTC, Kevoniat approved these changes

2023-03-11 18:51 UTC, noman2002 approved these changes

2023-03-11 18:55 UTC, merged