Populating organizationsBlockedBy when query called by Admin/Superadmin
PalisadoesFoundation/talawa-api pull request #1194
Opened 2023-03-17 18:28 UTC by prathamesh-mutkure

**What kind of change does this PR introduce?**

Bugfix

**Issue Number:**

Fixes #1186

**Did you add tests for your changes?**

Yes

**Snapshots/Videos:**

NA

**If relevant, did you update the documentation?**

Not Relevant

**Summary**

The problem -

- The User and Users queries have organizationsBlockedBy set to an empty array
- This is done on purpose so that users are not able to see which organizations they've been blocked by
- This breaks the Block/Unblock functionality in Talawa Admin

Solution -

- Now, the user needs to be authenticated to call `USERS` query
- If the user role is `ADMIN` or `SUPERADMIN`, then we are populating the `organizationsBlockedBy` field
- Otherwise returning `[]`
- We are also checking if the user is querying on themselves, and returning `[]` in that case

**Does this PR introduce a breaking change?**

No

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

Yes

2023-03-17 20:51 UTC, palisadoes commented
Please fix the failing tests

2023-03-18 11:52 UTC, prathamesh-mutkure commented
Hi @palisadoes, the tests have been fixed

2023-03-19 18:34 UTC, noman2002 approved these changes

2023-03-19 18:58 UTC, palisadoes approved these changes

2023-03-19 18:58 UTC, palisadoes requested changes
Please fix the conflicting files. We cannot merge this

2023-03-19 19:22 UTC, prathamesh-mutkure commented
Hi @noman2002, I've fixed merge conflicts, could you please approve this again? Thanks :)

2023-03-19 19:28 UTC, prathamesh-mutkure commented
@palisadoes fixed the merge conflics

2023-03-19 19:55 UTC, merged