tests for file `src/resolvers/Query/eventsByOrganizationConnection.ts`
PalisadoesFoundation/talawa-api pull request #1204
Opened 2023-03-19 17:32 UTC by KrutikaBhatt

**What kind of change does this PR introduce?**
This Pull Request includes tests written for file `src/resolvers/Query/eventsByOrganizationConnection.ts`. The test cases are covered for for all the functionalities and cases in the file

**Issue Number:** #1159 
This PR closes #1159

**Did you add tests for your changes?  Yes** 

**Snapshots/Videos:**
The code coverage obtained is 100%.
![image](https://user-images.githubusercontent.com/65107474/226195440-3a82d3ca-38a2-4ae6-9bab-4cdfa861fd41.png)
**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?** Yes

2023-03-19 18:30 UTC, noman2002 approved these changes

2023-03-19 18:31 UTC, noman2002 requested changes
Please fix the failing test.

2023-03-19 18:31 UTC, KrutikaBhatt commented
Yes, I am on it

2023-03-19 19:56 UTC, palisadoes approved these changes

2023-03-20 16:23 UTC, noman2002 approved these changes

2023-03-20 16:24 UTC, merged