Newsfeed management Updated and required changes
PalisadoesFoundation/talawa-api pull request #1383
Opened 2023-09-06 18:38 UTC by aashimawadhwa

**What kind of change does this PR introduce?**
Feature Enhancement

**Issue Number:** 

Fixes #1370 

**Did you add tests for your changes?**

Yes
**Snapshots/Videos:**
NA

**If relevant, did you update the documentation?**
NA

**Summary**
Implementation for the new additional features for the news feed management

 Changes :

Implementation of video post in news feed
Implementation of pin and unpin post
Implementation of updating photo and video of newsfeed

**Does this PR introduce a breaking change?**
No

**Other information**
NA

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**
Yes

2023-09-08 01:08 UTC, ttaylor92 approved these changes

2023-09-08 17:17 UTC, palisadoes commented
@aashimawadhwa Please get the code coverage back to an acceptable level.

2023-09-08 17:17 UTC, palisadoes requested changes
@aashimawadhwa Please get the code coverage back to an acceptable level.

2023-09-20 14:47 UTC, palisadoes approved these changes

2023-09-20 14:47 UTC, merged