Added query comments by post
PalisadoesFoundation/talawa-api pull request #1467
Opened 2023-12-07 00:55 UTC by imshivam-gupta

**What kind of change does this PR introduce?**

**Issue Number:**

Fixes #1460 

**Did you add tests for your changes?**

**Snapshots/Videos:**

![image](https://github.com/PalisadoesFoundation/talawa-api/assets/93479496/2a07151c-5f0a-4eda-8b24-a688b5a0142e)

**If relevant, did you update the documentation?**
No

**Summary**

Comments in app were not visible because it was expecting query commentsByPost which was not available. This PR added this feature so that all comments can be rendered for a particular post.

**Does this PR introduce a breaking change?**

No

**Other information**
N/A

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**
Yes

2023-12-07 01:25 UTC, imshivam-gupta commented
@noman2002 @palisadoes When i run npm run lint:fix i am getting no error

![image](https://github.com/PalisadoesFoundation/talawa-api/assets/93479496/a449954c-cc81-4572-85e8-83bedced71ee)

but in this bot I am getting error

![image](https://github.com/PalisadoesFoundation/talawa-api/assets/93479496/2ca945c8-13c2-4238-85ee-7a9179c79c9a)

Can you please suggest what to do here.

2023-12-07 05:28 UTC, noman2002 commented
@imshivam-gupta Fix the failing test.

2023-12-07 12:24 UTC, imshivam-gupta commented
@noman2002 Can you please tell how to add .eslintrc.json linting options because it will require additional dependencies.

2023-12-07 12:50 UTC, EshaanAgg commented
@imshivam-gupta Instead of linting `schema.graphql`, you should configure it to be ignored by ESLint as it does not need to be linted as it is autogenerated.

2023-12-07 12:58 UTC, imshivam-gupta commented
Yes but after changing eslint graphql is linting fine but since I changed eslint then it is asking for lining the json file and that will be the case if I add graphql to ignore in eslint.

2023-12-07 16:18 UTC, EshaanAgg requested changes

2023-12-07 16:18 UTC, EshaanAgg commented on .eslintrc.json
> +    },
Remove this rule.

2023-12-07 16:18 UTC, EshaanAgg commented on src/resolvers/Query/commentsByPost.ts
Please add the tests for this as well.

2023-12-07 17:19 UTC, imshivam-gupta commented
@EshaanAgg I have added the test for ```commentsByPost``` and performed the above changes.

2023-12-07 18:10 UTC, imshivam-gupta commented on .eslintignore
> +.eslintrc.json
Done

2023-12-07 20:21 UTC, EshaanAgg approved these changes

2023-12-07 20:35 UTC, imshivam-gupta commented
@EshaanAgg I guess during last commit I by mistake put a backspace and that one space caused prettier to fail. I fixed it. Sorry for the inconvenience.

2023-12-07 20:40 UTC, imshivam-gupta commented
Typescript failure is there for node_modules which can't be corrected from my side. What to do now?

2023-12-07 20:44 UTC, EshaanAgg commented
@imshivam-gupta Pull the latest changes. I have corrected the workflow file.

2023-12-07 20:50 UTC, EshaanAgg commented
@imshivam-gupta You might need to pull the changes again. There was a typo, which I have now corrected.

2023-12-07 20:54 UTC, imshivam-gupta commented
@EshaanAgg these are my final changes. I have performed all checks locally also but still not getting why checking for unauthorized file changes fails

2023-12-07 21:03 UTC, imshivam-gupta commented
@EshaanAgg the files for which I wrote test are having 100% coverage but the coverage dropped in 1 of files which I didn't change at all.

2023-12-07 21:05 UTC, EshaanAgg approved these changes

2023-12-07 22:31 UTC, palisadoes commented
@xoldyckk Please review

2023-12-08 11:47 UTC, xoldyckk commented
The PR also doesn't account for pagination and simply exposes the complete list of comments on a particular post. Imagine the client app fetching `999999` comments at once, this would lead to a server/database crash.

It is also a graphql anti-pattern, because it doesn't make use of the relation between a `Post` and the `Comment` created on that post to query related data. Instead of simply exposing `Post.comments` on a `Post` type it exposes a `Query.commentsByPostId` on root `Query` type. It makes the usage of graphql pointless since it's doing the same thing a REST api would, exposing a particular entity on a particular endpoint, providing no way to fetch along with it other entities related to it.

I have talked about these points before as well, in [discussions](https://github.com/PalisadoesFoundation/talawa-api/discussions) tab.

2023-12-08 12:29 UTC, imshivam-gupta commented
The complete app logic is built upon rendering complete data at a time. If we want to update that we have to modify a major chunk of the code to support the request to the server on scroll so that server load is reduced but I created this issue to create a graphql query expected on server side

2023-12-08 20:55 UTC, palisadoes commented
@xoldyckk I agree, we need to reduce the long term technical debt. Over the past 12 months we have been working hard to create a sustainable code base.
@imshivam-gupta Please resubmit according to the recommendations of @xoldyckk

2023-12-08 20:56 UTC, palisadoes requested changes
@xoldyckk I agree, we need to reduce the long term technical debt. Over the past 12 months we have been working hard to create a sustainable code base.
@imshivam-gupta Please resubmit according to the recommendations of @xoldyckk

2023-12-09 12:28 UTC, imshivam-gupta commented
Ok I will work on this.

2023-12-10 14:49 UTC, imshivam-gupta commented
@xoldyckk Can you please confirm if I should fetch all the comments with the post only and remove this query?

2023-12-10 17:39 UTC, xoldyckk commented
@imshivam-gupta Yes, and it should also be paginated using a graphql connection.

2023-12-11 12:14 UTC, imshivam-gupta commented
I have checked the existing GraphQL schema and confirmed that it already satisfies the requirements for commentsByPost. There was no need for a separate query. I opened this issue initially to create APIs for the frontend, but I now realize that updating the frontend queries suffices. Thanks @xoldyckk  for providing this insight; it was overlooked by me earlier. I also noticed that the Talawa-API has many redundant queries, for which I will definitely create issues in the future. This way, we can maintain sustainable code without the need for additional queries. @palisadoes I am closing this pull request and will chnage the frontend query directly to fetch the comments.

2023-12-11 12:14 UTC, closed without merging