fix md_mpx_format_adjuster.py script
PalisadoesFoundation/talawa-api pull request #1594
Opened 2023-12-29 09:52 UTC by dhiraj0911

**What kind of change does this PR introduce?**

- Bugfix for the automated documentation GitHub action PUSH workflow.
- Standardizes package manager to `npm` for both `talawa-api` and `talawa-admin`.
- Adds a Python script (`md_mpx_format_adjuster.py`) to ensure Markdown files are MPX compatible.

**Issue Number:** #1559 

---

**Did you add tests for your changes?**

- No new tests added. The changes pertain to the GitHub Actions workflow and documentation updates.
- Manual testing was conducted to ensure functionality and MPX compatibility.

---

**If relevant, did you update the documentation?**

- Documentation updated to reflect the shift from npm to yarn and the integration of `script.py`.
- Details on workflow changes and MPX compatibility considerations with Docusaurus v3 included.

---

**Summary**

- Addresses issues with GitHub action for automated documentation generation.
- Resolves inconsistencies in package managers and non-compliance with Docusaurus v3's MPX standards.
- Includes transition to yarn and introduction of `script.py` for Typedoc-generated Markdown files.

---

**Does this PR introduce a breaking change?**

- No breaking changes introduced.
- Focuses on resolving workflow issues and enhancing compatibility, not affecting core software functionality.

---

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

- Yes, the contributing guidelines have been followed.

2023-12-29 19:00 UTC, palisadoes commented
Please work with @noman2002 on this. He'll be taking over the review of this PR

2024-01-01 04:09 UTC, palisadoes commented
@Nitya-Pasrija Please be aware of this PR

2024-01-01 04:10 UTC, palisadoes commented
Please fix the conflicting file

2024-01-01 05:05 UTC, Nitya-Pasrija commented
On it

2024-01-02 00:10 UTC, palisadoes requested changes
1. See comment
2. Have you determined whether the API workflow is updating the Talawa-Docs repository?

2024-01-02 00:10 UTC, palisadoes commented on INSTALLATION.md
> +- [Talawa-API Installation](#talawa-api-installation)
This file must not be included in this PR

2024-01-02 00:12 UTC, palisadoes commented
Please fix the conflicting files

2024-01-04 22:15 UTC, palisadoes commented
@dhiraj0911 

1. Please fix the conflicting files.
2. Have you tested this exporting to Talawa-Docs

2024-01-05 06:04 UTC, dhiraj0911 commented
I've changed destination_branch to `develop` to see changes but not appearing there as verify-workflow branch was not there

2024-01-05 06:25 UTC, palisadoes commented
Please reach out to Noman on Slack to schedule a time over the weekend for both of you to troubleshoot this. He's very busy during the week. Both of you are in the same time zone so it will be easier to fix it quickly

2024-01-05 06:51 UTC, dhiraj0911 commented
Okay, thanks

2024-01-08 03:59 UTC, palisadoes commented
@dhiraj0911

1. Please fix the conflicting files
2. Have you managed to contact @noman2002?
3. You still haven't reported confirmation that the workflow is copying files to `Talawa-Docs` successfully

2024-01-08 04:17 UTC, dhiraj0911 commented
Yes, I messaged him on slack waiting for his reply

2024-01-08 04:18 UTC, dhiraj0911 commented
Till now I would like to contribute to other issues, can you assign them to me?

2024-01-08 04:49 UTC, palisadoes commented
> Till now I would like to contribute to other issues, can you assign them to me?

I've assigned the original issue to myself

2024-01-19 01:16 UTC, closed without merging