Update @apollo/server version from 4.9.3 --> 4.9.5
PalisadoesFoundation/talawa-api pull request #1597
Opened 2023-12-29 17:57 UTC by Sahil-Shadwal

**What kind of change does this PR introduce?**

Updated @apollo/server version from 4.9.3 --> 4.9.5

**Issue Number:**

Fixes #1593 

**Did you add tests for your changes?**

No

**Snapshots/Videos:**

**If relevant, did you update the documentation?**

No

**Summary**

Motivation for the Change:

- A major bug was identified in Apollo Server v4.9.3 currently in use.

- Bug details outlined in the repository's changelog.

- Proposed solution: Upgrade Apollo Server to v4.9.5 and GraphQL to at least v16.7.0.

- Suggested completion criteria: Consider using the latest version, v16.8.1. 

This pull request addresses the issue #1593 

**Does this PR introduce a breaking change?**

No

**Other information**

- GraphQl was already v16.8.1 so didn't needed to change that.

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

Yes i have.

2023-12-29 19:05 UTC, palisadoes commented
You have not completed the steps in the issue. Please read the instructions carefully

2023-12-30 18:35 UTC, Sahil-Shadwal commented
> You have not completed the steps in the issue. Please read the instructions carefully

Sorry for that let me correct that !

2024-01-02 20:40 UTC, sumitra19jha commented
Good to merge.

2024-01-02 20:41 UTC, sumitra19jha approved these changes

2024-01-02 20:52 UTC, palisadoes requested changes
@Sahil-Shadwal You have not upgraded GraphQL as was requested

2024-01-03 17:24 UTC, xoldyckk commented
@palisadoes why not just enable dependabot automated updates on this repository?

2024-01-03 17:28 UTC, palisadoes commented
1. We have it.
2. This one was not triggered by Dependabot which seems to be lagging. I happened to check the Apollo site and saw this.
3. Also this change requires simultaneous updates in two packages which usually causes our tests to fail.

2024-01-04 16:43 UTC, palisadoes commented
@Sahil-Shadwal Are you still working on this?

2024-01-05 15:35 UTC, palisadoes commented
I have to close this and unassign the issue because there has been no response for some time

2024-01-05 15:35 UTC, closed without merging