Removes {} from console logging
PalisadoesFoundation/talawa-api pull request #1608
Opened 2023-12-31 04:59 UTC by RAGHAV-N5

**What kind of change does this PR introduce?**

Bugfix

**Issue Number:**

Fixes #1549 

**Did you add tests for your changes?**

No

**Snapshots/Videos:**

![Screenshot 2023-12-31 101654](https://github.com/PalisadoesFoundation/talawa-api/assets/135726978/c85e1e9f-93b5-466c-aee5-029dd5e68552)

**If relevant, did you update the documentation?**

No

**Summary**

This PR aims to remove {} from the console logging which was not necessary. 

**Does this PR introduce a breaking change?**

No

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

Yes

2023-12-31 17:20 UTC, noman2002 requested changes
Fix the failing test.

2024-01-01 01:06 UTC, RAGHAV-N5 commented
@noman2002 Can you please help me how to proceed to fix the failing tests?

2024-01-01 03:37 UTC, palisadoes commented
Please read the error messages the answer should be there.

2024-01-01 04:11 UTC, RAGHAV-N5 commented
@palisadoes 
Are these the ones I should fix?
![Screenshot 2024-01-01 093839](https://github.com/PalisadoesFoundation/talawa-api/assets/135726978/ff287d4d-a77d-4610-8159-6422bc4f535f)

2024-01-01 04:15 UTC, palisadoes commented
Please click on the link to read the cause of the failure.

![image](https://github.com/PalisadoesFoundation/talawa-api/assets/16875803/87bb10f6-6170-433c-94ce-48ab375d11ba)

2024-01-01 05:22 UTC, palisadoes requested changes
See comments

2024-01-01 05:22 UTC, palisadoes commented on setup.ts
> -// Check connection to Redis with the specified URL.
1. There is no need to have this file included in this PR
1. You have also removed key functionality in it.
1. Exclude this file from the PR
1. Merge with the latest upstream also

2024-01-01 06:47 UTC, RAGHAV-N5 commented
@palisadoes
 I was using nodejs version of 21.4.0 but after carefully examining the workflow files I found that node js [20.x] was used. 
 So, this is causing the tests to fail. Please correct me if I'm wrong.

2024-01-01 15:51 UTC, palisadoes commented
> @palisadoes I was using nodejs version of 21.4.0 but after carefully examining the workflow files I found that node js [20.x] was used. So, this is causing the tests to fail. Please correct me if I'm wrong.

Please use your initiative to see whether that is the cause.

2024-01-03 12:25 UTC, closed without merging