Add support for Action Items
PalisadoesFoundation/talawa-api pull request #1648
Opened 2024-01-07 15:33 UTC by meetulr

Fixes #1595 

**Did you add tests for your changes?**

Yes

**Summary**

This pull request introduces the following changes:
1. **Support for Categories:** Create, Read, and Update (CRU) operations have been added for Categories. This feature is accessible to superAdmins and orgAdmins.
2. **Support for Action Items:** Create, Read, Update, and Delete (CRUD) operations have been added for Action Items. This feature is accessible to superAdmins, orgAdmins, and eventAdmins.
3. **Category-Organization Relationship:** A two-way relationship has been established between Categories and Organizations. A default Category is automatically created and associated with each newly created Organization. Additionally, any new Categories created are automatically associated with the corresponding Organization.
4. **ActionItem-Event Relationship:** A two-way relationship has been established between Action Items and Events. If an Action Item is associated with an Event, it is automatically added to that Event. If an Action Item is deleted, it is automatically removed from the associated Event. Furthermore, if an Event is deleted, all associated Action Items are also deleted.
5. **Organization Cascade Delete Functionality:** Upon deletion of an Organization, all Categories associated with the Organization, as well as all Action Items associated with those Categories, are automatically deleted.
6. **Comprehensive Testing:** Tests have been added to ensure full coverage for all newly added or modified files.

**Does this PR introduce a breaking change?**

No

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

Yes

2024-01-07 15:37 UTC, meetulr commented
I've had fun implementing this. Let me know for any changes that are required, or anything I might have missed.
Thanks.

2024-01-07 16:01 UTC, palisadoes commented
Just to confirm, did you implement Action Items related to Events and to Users independent of events?

2024-01-07 16:03 UTC, meetulr commented
> Just to confirm, did you implement Action Items related to Events and to Users independent of events?

I didn't restrict the assigment of an action item to specific users, that means it could be assigned to anyone, regardless them being involved with the event or not.

2024-01-08 17:50 UTC, palisadoes commented
- @xoldyckk
- @sumitra19jha
- @DMills27
- @xsh2047

Please review

2024-01-11 16:11 UTC, palisadoes commented
Please fix the conflicting file

2024-01-12 14:41 UTC, meetulr commented
Could this be reviewed please...
Sorry for asking like this😅.

2024-01-12 17:32 UTC, palisadoes commented
Reviewers:

- @xoldyckk
- @sumitra19jha
- @DMills27
- @xsh2047
- @JamaicanFriedChicken 

This is ready for review.

2024-01-17 12:39 UTC, meetulr commented
Resolved the conflicts.
Requesting review!😅

2024-01-17 12:49 UTC, sumitra19jha commented
You have done changes in so many files. I will like too see a video recording as well of the working prototype in local.

2024-01-17 12:56 UTC, meetulr commented
> You have done changes in so many files. I will like too see a video recording as well of the working prototype in local.

Almost all of the files are new, as it's a new feature.
The frontend for this has not yet been implemented.
Do you mean a demo in sandbox?
I have written tests for all the files too, and they're covering everything, and passing.

Shall I create an issue in admin for this? @palisadoes

2024-01-19 05:14 UTC, palisadoes commented
@meetulr 

Yes prototype Admin screens for evaluation would be very helpful.

2024-01-19 05:17 UTC, palisadoes commented
We should merge this prior to the Talawa Admin prototype after a review based on best practices. The admin prototype will highlight any broken functionality

Please review based on this assessment:

1. @xoldyckk
1. @sumitra19jha
1. @DMills27
1. @xsh2047
1. @JamaicanFriedChicken

2024-01-19 15:21 UTC, meetulr commented
> @meetulr
> 
> Yes prototype Admin screens for evaluation would be very helpful.

Alright! I'll soon open an issue in admin for action items with my proposed solution, and if approved, I'll proceed with the implementation.

2024-01-19 15:21 UTC, meetulr commented
> > @meetulr
> > Yes prototype Admin screens for evaluation would be very helpful.
> 
> Alright! I'll soon open an issue in admin for action items with my proposed solution, and if approved, I'll proceed with the implementation right away.

2024-01-19 17:36 UTC, xoldyckk commented on src/models/ActionItem.ts
> +  assignedTo: PopulatedDoc<InterfaceUser & Document>;
rename to `assigneeId`

2024-01-19 17:36 UTC, xoldyckk commented on src/models/ActionItem.ts
> +  assignedBy: PopulatedDoc<InterfaceUser & Document>;
rename to `assignerId`

2024-01-19 17:36 UTC, xoldyckk commented on src/models/ActionItem.ts
> +  completed: boolean;
rename to `isCompleted`

2024-01-19 17:36 UTC, xoldyckk commented on src/models/ActionItem.ts
> +  createdBy: PopulatedDoc<InterfaceUser & Document>;
rename to `creatorId`

2024-01-19 17:36 UTC, xoldyckk commented on src/models/ActionItem.ts
> +const actionItemSchema = new Schema(
confirm which fields are non nullable and add `required: true` field to them

2024-01-19 17:36 UTC, xoldyckk commented on src/models/Category.ts
> +    category: {
rename to `name`

2024-01-19 17:36 UTC, xoldyckk commented on src/models/Category.ts
> +    orgId: {
rename to `organizationId`

2024-01-19 17:36 UTC, xoldyckk commented on src/models/Category.ts
> +      default: false,
rename to `isDisabled`, `required: true`

2024-01-19 17:36 UTC, xoldyckk commented on src/models/Category.ts
> +    createdBy: {
rename to `creatorId`

2024-01-19 17:36 UTC, xoldyckk commented on src/models/Category.ts
> +export interface InterfaceCategory {
Category is a very generic term, should be named something specific

2024-01-19 17:36 UTC, xoldyckk commented on src/models/ActionItem.ts
> +export interface InterfaceActionItem {
should probably be named `UserAction`?

2024-01-19 17:36 UTC, xoldyckk commented on src/models/Event.ts
> +    actionItems: [
get rid of this, relationship to an event is already present on `ActionItem` using `eventId` field

2024-01-19 17:36 UTC, xoldyckk commented on src/models/Organization.ts
> +    actionCategories: [
get rid of this, relationship to an organization is already present on `Category` using `organizationId` field

2024-01-19 17:36 UTC, xoldyckk commented on src/models/Category.ts
> +import type { PopulatedDoc, Types, Document, Model } from "mongoose";
create a compound unique constraint on `category.organzationId` and `category.name`(category.category here)

2024-01-20 03:00 UTC, meetulr commented
Thank you! I'll make the necessary changes.

2024-01-20 03:03 UTC, meetulr commented
@palisadoes Shall I rename Category to ActionCategory, and ActionItem to UserAction?

2024-01-20 03:07 UTC, palisadoes commented
The category should be renamed. Action Item should remain

2024-01-20 03:10 UTC, palisadoes commented
1. The category should be renamed. Action Item Category to prevent any ambiguity
1. Action Item should remain

2024-01-22 15:37 UTC, palisadoes commented
@meetulr 

1. Let us know when this is ready to be reviewed.
2. Mark the comments that have been rectified as being resolved

2024-01-22 15:58 UTC, palisadoes commented
This is ready for review. Please take a look.

1. @xoldyckk
1. @sumitra19jha
1. @DMills27
1. @xsh2047
1. @JamaicanFriedChicken
1. @EshaanAgg

2024-01-27 07:18 UTC, meetulr commented
This is a sandbox demo of the mutations and queries I made:

1. **For Action Item Categories**:

https://github.com/PalisadoesFoundation/talawa-api/assets/55585268/02f61ddb-e424-4773-9493-d43513cb0f72

2024-01-27 07:32 UTC, meetulr commented
This is a sandbox demo for the changes I made:

1. **For Action Item Categories**:

https://github.com/PalisadoesFoundation/talawa-api/assets/55585268/4c5ddd2d-bba3-49d5-9096-fbccf2301f12

2024-01-27 07:46 UTC, SiddheshKukade commented
I'll test it out and let you know.

2024-01-27 08:57 UTC, meetulr commented
> This is a sandbox demo for the changes I made:
> 
> 1. **For Action Item Categories**:
> 
>  actionItemCategory.mp4 
> 2. **For Action Items**:
> 
>  actionItems.mp4

@xoldyckk 
@sumitra19jha 
@EshaanAgg 
@DMills27 
@JamaicanFriedChicken 

The frontend for this is now in development, any changes made/required here would have an impact there too.
Please take a look!😅
Thank you.

2024-01-27 08:57 UTC, meetulr commented
> I'll test it out and let you know.

Thank you!

2024-01-28 07:22 UTC, EshaanAgg requested changes
Just a minor suggestion.

2024-01-28 07:22 UTC, EshaanAgg commented on src/models/ActionItem.ts
> +      default: Date.now() + 7 * 24 * 60 * 60 * 1000,
Due to use constants inline such as `7 * 24 * ....`. Define it in `constants.ts` and then import and use the same here.

2024-01-28 08:40 UTC, meetulr commented
> Just a minor suggestion.

Thank you! I've made the change, and I'll keep that in mind.

2024-01-28 08:54 UTC, palisadoes commented
@EshaanAgg please review the updates

2024-01-28 17:19 UTC, EshaanAgg approved these changes

2024-01-28 17:22 UTC, palisadoes approved these changes

2024-01-28 17:22 UTC, merged