feat : Fundraising campaign
PalisadoesFoundation/talawa-api pull request #1708
Opened 2024-01-16 20:35 UTC by saswat10

**What kind of change does this PR introduce?**
Feature

**Issue Number:** -->  #1663 Add Support of Fundraising Campaigns

**Did you add tests for your changes?** --> Yes

**Summary**
This Pull Request introduces the addition of *fundraising campaigns* schema and the required CRUD operations , along with the test files.

**Does this PR introduce a breaking change?** --> No

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?** --> Yes

2024-01-16 21:57 UTC, palisadoes commented
Please fix the conflicting files

2024-01-17 12:34 UTC, sumitra19jha commented
Please fix the conflict for review

2024-01-17 12:49 UTC, saswat10 commented
> Please fix the conflict for review

Do I need to fix it? Cause it shows I don't have the write access

2024-01-18 18:25 UTC, saswat10 commented
Please can you look at the Pull Request, I have resolved the conflicts in the files.

2024-01-19 04:01 UTC, palisadoes requested changes
@saswat10 

1. Restore .husky/post-merge
2. Restore .husky/pre-commit

They are an integral part of our code quality process. You will need to make sure your code complies with our linting standards.

1. Do this immediately. We will not assign reviewers until this is done.
2. This is why the linting tests are failing in the PR
3. It is also why the authorized access test and application tests are failing

2024-01-19 04:33 UTC, saswat10 commented
@palisadoes  please check now, I have made necessary changes.

2024-01-19 05:02 UTC, palisadoes commented
1. You need to make sure all your linting tests pass or else the PR tests will never pass.
2. Then when the linting passes, you'll need to make sure the other tests pass and that the code coverage doesn't decline. We are at close to 97% testing coverage and we cannot afford to make that drop below our 95% target. The code was really buggy in the past and the tests have made it significantly better.
3. Make sure to test before submitting further updates and verify the test code coverage in your local repo. The CONTRIBUTING.md file goes over this.

It's difficult for us to be constantly approving the workflows for every minor commit. 

Please take the time to have better testing and linting before the next commit.

2024-01-19 05:03 UTC, palisadoes commented
FYI. Fix these first

![image](https://github.com/PalisadoesFoundation/talawa-api/assets/16875803/4fb80749-2ce5-427b-b785-b44bd8abb680)

2024-01-21 03:27 UTC, palisadoes commented
@saswat10 How is progress on this?

2024-01-21 03:33 UTC, palisadoes commented
We need to have this implemented soon. See the comments above

2024-01-21 04:38 UTC, saswat10 commented
> 1. How is progress on this?

 Currently working on it.

> 2. Why has the definition for the Fund not been submitted?

Will raise a PR by tomorrow.

> 3. Why doesn't the FundCampaign refer to a Fund in the Schema?

Since you said that fund campaign cannot have more than one associated funds. But will I will add a Fund schema which would refer to the parent fund  in the fund campaign. 
![image](https://github.com/PalisadoesFoundation/talawa-api/assets/104200293/c5c31c02-62bd-4d06-ba9a-389caed6cf09)

2024-01-21 04:56 UTC, palisadoes commented
We agreed on your proposed schema.

```
Funds can have many associated campaigns and not vice versa
```

ie. Campaigns can only be associated with one fund.

It would be good to see the end result of your work. We have a few follow up issues that depend on this one being completed.

2024-01-22 06:30 UTC, palisadoes commented
Where is the fund in the schema? This does not comply with the issue requirements.

2024-01-22 06:43 UTC, saswat10 commented
> Where is the fund in the schema? This does not comply with the issue requirements.
 
I haven't  tested that code yet, It is in a different branch , I will add by today positively.

2024-01-27 15:02 UTC, palisadoes commented
Why was this closed? We have spent so much time reviewing you work.

2024-01-27 16:21 UTC, saswat10 commented
> Why was this closed? We have spent so much time reviewing you work.

I was checking for the workflow
Making minor commits can send message to the reviewer, hence I closed the issue


I have reopened the issue, but made it into a draft

2024-01-27 16:55 UTC, palisadoes commented
1. We don't accept draft PRs.
1. We get notifications with every commit and comment no matter the type of PR.

Convert to a regular PR or close this and practice on your forked repository

2024-01-27 16:57 UTC, palisadoes commented
You can test on your local repo. We have to separately approve each of your commits

2024-01-27 16:58 UTC, palisadoes commented
Let us know when you are ready

2024-01-27 17:04 UTC, palisadoes commented
We are not going to review a draft PR

2024-01-27 22:44 UTC, palisadoes commented
@sumitra19jha @xoldyckk @EshaanAgg @JamaicanFriedChicken 

This is ready for review

2024-01-28 15:39 UTC, palisadoes commented
Please fix the failing tests. Our test code coverage system will fail if any of these conditions occur:

1) The overall code coverage drops below the target threshold of the repository
2) Any file in the pull request has code coverage levels below the repository threshold

We do this to ensure the overall reliability of the code base is maintained. This is a prerequisite for getting your PR approved. Assigned reviewers regularly review the PR queue and tend to focus on PRs that are passing.

2024-01-28 16:51 UTC, saswat10 commented
> Please fix the failing tests. Our test code coverage system will fail if any of these conditions occur:
> 
> 1. The overall code coverage drops below the target threshold of the repository
> 2. Any file in the pull request has code coverage levels below the repository threshold
> 
> We do this to ensure the overall reliability of the code base is maintained. This is a prerequisite for getting your PR approved. Assigned reviewers regularly review the PR queue and tend to focus on PRs that are passing.

Ok. Working on it

2024-02-03 02:55 UTC, palisadoes commented
Please address the decline in code test coverage.

2024-02-05 17:22 UTC, saswat10 commented
@palisadoes I'm facing a problem, the autogenerated schema for the fund schema is bit weird like

![image](https://github.com/PalisadoesFoundation/talawa-api/assets/104200293/f92b0de0-1730-4325-95ed-edf84d074fe9)
 
Due to this whatever test case I'm writing for the FundCampaign helper functions, it is showing errors....

Why can't I get something simpler auto generated schema like this

![image](https://github.com/PalisadoesFoundation/talawa-api/assets/104200293/f60950e8-f682-4b3e-8596-33cb3539fd9f)
![image](https://github.com/PalisadoesFoundation/talawa-api/assets/104200293/cd3bc6e7-ebe2-48cd-b5f7-634333a4ca3e)

2024-02-05 17:29 UTC, saswat10 commented
> @palisadoes I'm facing a problem, the autogenerated schema for the fund and fund campaign schemas is bit weird like
> 
> ![image](https://private-user-images.githubusercontent.com/104200293/302375202-f92b0de0-1730-4325-95ed-edf84d074fe9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxNTQ0MTksIm5iZiI6MTcwNzE1NDExOSwicGF0aCI6Ii8xMDQyMDAyOTMvMzAyMzc1MjAyLWY5MmIwZGUwLTE3MzAtNDMyNS05NWVkLWVkZjg0ZDA3NGZlOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNVQxNzI4MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04OTBjMWUyY2MwNjcxNWYwOWFiZDQyN2Y0YTY4YmIxNjMxNmIwNjFjYzYwMzUwYjM1MjQ0ODAzMWQxYzg0ZmUyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.85xXFphVZ1841T5isYvUICMEJ7GRaXwvyZuT9LBomkM)
> 
> Due to this whatever **test case I'm writing for the FundCampaign helper functions, it is showing errors....**
> 
> I not getting something simpler auto generated schema like this
> 
> ![image](https://private-user-images.githubusercontent.com/104200293/302375596-f60950e8-f682-4b3e-8596-33cb3539fd9f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxNTQ0MTksIm5iZiI6MTcwNzE1NDExOSwicGF0aCI6Ii8xMDQyMDAyOTMvMzAyMzc1NTk2LWY2MDk1MGU4LWY2ODItNGIzZS04NTk2LTMzY2IzNTM5ZmQ5Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNVQxNzI4MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ODE2YjAxYTNkZDI4YTMyMzU3MTg0MmJkYTY0MGYyYTIyZTIyYzI3Njc2ZjY0OTQ0OTI0NGU3OGYxNTEwMzI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MEfXwU2pzSfs68WU9kvTg3br9g7kAkRTmq88Lw1MBjQ) ![image](https://private-user-images.githubusercontent.com/104200293/302375643-cd3bc6e7-ebe2-48cd-b5f7-634333a4ca3e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxNTQ0MTksIm5iZiI6MTcwNzE1NDExOSwicGF0aCI6Ii8xMDQyMDAyOTMvMzAyMzc1NjQzLWNkM2JjNmU3LWViZTItNDhjZC1iNWY3LTYzNDMzM2E0Y2EzZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNVQxNzI4MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZTQ4NGY0Y2ViMDYwN2RiYjdlYTk0MGQ2MmU4MjdhOGZjNjNiZjJiYjA0Nzk4ODZhN2QwMTA2MzBhNDE2MzRjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.j98DWx-2psx0vxL7_EhMKSkxULrlJRw1LYAxIWu5rP0)

Due to this I had skipped writing test case for the Fund Campaign helper functions like creator.ts, fund.ts and pledge.ts

2024-02-05 19:27 UTC, EshaanAgg requested changes
I am not very sure about the organization of the three models and how their hierarchy would be, so I may have added some not-null assertions where they may be nullable, so please take this review with caution. But the fact remains that you need to update the type definitions as mentioned here. 

Also, please try to make smaller PRs. Ideally, you should only add the schema definitions and typedefs in a PR, and open a PR for every 2-3 resolvers. It is not possible to holistically review a PR of this size. Please keep this in mind for the next time.

2024-02-05 19:27 UTC, EshaanAgg commented on schema.graphql
> +  campaigns: [FundCampaign]
You have not created the type definitions properly, which is leading to the items being nullable and thus, the type errors you are getting. Refer to the comments.

2024-02-05 19:27 UTC, EshaanAgg commented on src/models/CampaignPledge.ts
> +  campaigns: PopulatedDoc<InterfaceFundCampaign & Document>[];
How many members and campaigns is a CampaignPledge supposed to hold? Will it be a small number like 10-15, or can it be something infinitely scalable (that is something in the order of let's say 5% of members of the organization)? If it's the later, we should be using a joining table and not the direct embedding of ducments.

2024-02-05 19:27 UTC, EshaanAgg commented on src/models/FundCampaign.ts
> +  pledgeId: PopulatedDoc<InterfaceCampaignPledge & Document>;
Many fields are repeated between the models `Fund`, `FundCampaign` and `CampaignPlegde`. The relationship should be modelled through parent and children, and only the id of the parent should be stored on the children to reduce data redundancy.

2024-02-05 19:27 UTC, EshaanAgg commented on src/typeDefs/inputs.ts
> +    pledgeId: ID
Can these be `null`? Should the FundCampaign always be associated with a pledge or fund?

2024-02-05 19:27 UTC, EshaanAgg commented on src/typeDefs/mutations.ts
> +    addParentFundtoCampaign(data: addParentFund): FundCampaign @auth
```suggestion
    addParentFundtoCampaign(data: addParentFund!): FundCampaign! @auth
```

2024-02-05 19:27 UTC, EshaanAgg commented on src/typeDefs/mutations.ts
> +    addPledgeIDtoCampaign(data: addPledge): FundCampaign @auth
```suggestion
    addPledgeToCampaign(data: addPledge!): FundCampaign! @auth
```

2024-02-05 19:27 UTC, EshaanAgg commented on src/typeDefs/mutations.ts
> +    # createFund(data: FundInput): Fund! @auth
Remove this if this is a comment.

2024-02-05 19:27 UTC, EshaanAgg commented on src/typeDefs/mutations.ts
> +    updateFundCampaign(id: ID!, data: UpdateFundCampaignInput): FundCampaign!
```suggestion
    updateFundCampaign(id: ID!, data: UpdateFundCampaignInput!): FundCampaign!
```

2024-02-05 19:27 UTC, EshaanAgg commented on src/typeDefs/queries.ts
> +    getFundCampaigns: [FundCampaign]
No need for this. These should be implemented as a field level resolver either on the `Organization` model, or the other relevant parent models to `FundCampaign`

2024-02-05 19:27 UTC, EshaanAgg commented on src/typeDefs/types.ts
> +    creator: User
```suggestion
    creator: User!
```

2024-02-05 19:27 UTC, EshaanAgg commented on src/typeDefs/types.ts
> +    organization: Organization
```suggestion
    organization: Organization!
```

2024-02-05 19:27 UTC, EshaanAgg commented on src/typeDefs/types.ts
> +    campaigns: [FundCampaign]
```suggestion
    campaigns: [FundCampaign!]!
```

2024-02-05 19:27 UTC, EshaanAgg commented on src/typeDefs/types.ts
> +    creator: User
```suggestion
    creator: User!
```

2024-02-05 19:27 UTC, EshaanAgg commented on src/typeDefs/types.ts
> +    parentFundId: Fund
```suggestion
    parentFund: Fund!
```

2024-02-05 19:27 UTC, EshaanAgg commented on src/typeDefs/types.ts
> +    pledgeId: CampaignPledge
```suggestion
    pledge: CampaignPledge!
```

2024-02-05 19:27 UTC, EshaanAgg commented on src/typeDefs/types.ts
> +    creator: User
```suggestion
    creator: User!
```

2024-02-05 19:27 UTC, EshaanAgg commented on src/typeDefs/types.ts
> +    members: [User]
```suggestion
    members: [User!]!
```

2024-02-05 19:27 UTC, EshaanAgg commented on src/typeDefs/types.ts
> +    campaigns: [FundCampaign]
```suggestion
    campaigns: [FundCampaign!]!
```

2024-02-05 19:27 UTC, EshaanAgg commented on src/typeDefs/types.ts
> +    createdFundCampaigns: [FundCampaign]
```suggestion
    fundCampaigns: [FundCampaign!]!
```

2024-02-08 17:23 UTC, palisadoes commented
Please fix the conflicting files and address the reviewer requests

2024-02-14 21:52 UTC, palisadoes commented
When do you think this will be ready for review?

2024-02-16 15:51 UTC, sumitra19jha commented
Please resolve conflict

2024-02-16 17:55 UTC, palisadoes commented
*NOTE* Read very carefully

1. We just merged this PR which upgraded the prettier package. 
    1. https://github.com/PalisadoesFoundation/talawa-api/pull/1840
1. It reformatted over 400 files. This will put your PR at risk of extensive merge conflicts.    
1. I suggest that before you merge your code to the latest upstream, or manually fix these merge conflicts that you:
    1. upgrade your `prettier` in your local branch to the same version
    1. run `prettier`
    
This will help to reduce the number of future merge conflicts for your PR.

2024-02-18 15:51 UTC, palisadoes commented
Closing due to inactivity and the fact that this has been open for a month.

2024-02-18 15:51 UTC, closed without merging

2024-02-18 19:18 UTC, varshith257 commented
@palisadoes  Waiting for your update on this issue assignment. Please assign me this issue. I am eagerly waiting to contribute to this

2024-02-19 06:37 UTC, varshith257 commented
@palisadoes Waiting for the update on the assignment of the issue for quite a long time