Merge : inpect.yml into push.yml
PalisadoesFoundation/talawa-api pull request #1718
Opened 2024-01-18 16:15 UTC by aialok

**What kind of change does this PR introduce?**

- The current GitHub Actions configuration in the API repository involves two separate YAML files, namely inspect.yml and push.yml, both triggered on every push. To streamline and simplify the workflow, we propose consolidating the code from inspect.yml into push.yml and subsequently removing inspect.yml.

**Issue Number:**

Fixes #1696 

**Did you add tests for your changes?**

- No

**Snapshots/Videos:**

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

2024-01-19 04:15 UTC, palisadoes requested changes
See comment

2024-01-19 04:15 UTC, palisadoes commented on .github/workflows/push.yml
> +    name: Check Schema
This should depend on the success of `Push-Workflow` tests

2024-01-19 19:58 UTC, palisadoes commented
@noman2002 please review

2024-01-21 07:59 UTC, aialok commented
@palisadoes, Please have a look.

2024-01-21 20:13 UTC, palisadoes approved these changes

2024-01-21 20:13 UTC, merged

2024-01-21 20:28 UTC, palisadoes commented
This has to be reverted. It's failing. https://github.com/PalisadoesFoundation/talawa-api/actions/runs/7603568839/job/20705612488