Deprecated titles for non-pinned posts
PalisadoesFoundation/talawa-api pull request #1744
Opened 2024-01-26 14:23 UTC by pateldivyesh1323

**What kind of change does this PR introduce?**

**Issue Number: #1739**

Fixes #1739

Deprecated title for non-pinned posts

Following API endpoints are changed:
 
- Create post
- Update post
- Toggle post pin

Title should be provided to pin post. Non pinned posts will throw error if title is provided.

In toggle post pin, an input for title should be provided on the client side if the post is getting pinned, and the title will be automatically removed if the post is getting unpinned.

**Did you add tests for your changes?**

**Snapshots/Videos:**

**If relevant, did you update the documentation?**

No

**Does this PR introduce a breaking change?**

Yes

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

Yes

2024-01-26 19:05 UTC, palisadoes requested changes
See comments

2024-01-26 19:05 UTC, palisadoes commented on src/resolvers/Mutation/createPost.ts
> +  if (args.data?.title && !args.data.pinned) {
1. Pinned posts can only be created by Super Admins or Admins for the organization where the post was created.
2. Please make sure this logic is enforced

2024-01-26 19:05 UTC, palisadoes commented on src/resolvers/Mutation/updatePost.ts
> +    throw new errors.InputValidationError(
1. Pinned posts can only be created by Super Admins or Admins for the organization where the post was created.
2. Please make sure this logic is enforced

2024-01-26 19:05 UTC, palisadoes commented on tests/resolvers/Mutation/updatePost.spec.ts
> +    );
1. Pinned posts can only be created by Super Admins or Admins for the organization where the post was created.
2. Please make sure this logic is enforced

2024-01-26 19:05 UTC, palisadoes commented on tests/resolvers/Mutation/togglePostPin.spec.ts
> +    try {
1. Pinned posts can only be created by Super Admins or Admins for the organization where the post was created.
2. Please make sure this logic is enforced

2024-01-27 09:23 UTC, pateldivyesh1323 commented
@palisadoes It was already ensured that only admins and super-admin can only create pinned post and toggle pin/unpin posts.

![image](https://github.com/PalisadoesFoundation/talawa-api/assets/109150688/6c696030-1676-4ebd-941e-18b3af62975a)

![image](https://github.com/PalisadoesFoundation/talawa-api/assets/109150688/1eb077a7-ed35-404e-aac8-5597917844d3)

2024-01-28 07:27 UTC, EshaanAgg approved these changes

2024-01-28 07:55 UTC, palisadoes approved these changes

2024-01-28 07:55 UTC, merged