A new middleware function has been added to control the flow of erro…
PalisadoesFoundation/talawa-api pull request #181
Opened 2021-03-23 12:57 UTC by somya339

…rs and from now onwards the error throwing should follow the decorum mentioned in the documentation

**What kind of change does this PR introduce?**

Enhancement in the Error Handling mechanism

**Did you add tests for your changes?**
No tests were required for the changes that are introduced.
**If relevant, did you update the documentation?**
there is a need to update the documentation

2021-03-23 21:27 UTC, iamsaumya commented
Hey @somya339 , Do you mind if I review your PR? I was about the get this resolved, now as you are working on this issue I will like to extend my helping hand.

2021-03-24 04:22 UTC, Sagar2366 commented
@somya339 good job. Can you please add issue number with this PR.

2021-03-24 04:46 UTC, somya339 commented
@Sagar2366 now there is a need to update the documentation to follow the error throwing mechanism , should I create another pull request for that?

2021-03-24 04:50 UTC, Sagar2366 commented
> @Sagar2366 now there is a need to update the documentation to follow the error throwing mechanism , should I create another pull request for that?

Where do you want to update documentation ?

2021-03-24 05:44 UTC, somya339 commented
By Documentation I mean we have to Demonstrate  the use of this middleware somewhere such that it can be seen by all the contributors so that everyone is using " Apperror() " to throw error.

2021-04-28 15:31 UTC, palisadoes commented
@somya339  Please resolve the merge conflicts

2021-05-17 15:14 UTC, palisadoes commented
@somya339 We have since migrated to react. Is this PR in react?

2021-05-19 06:54 UTC, impiyush83 commented on error_middleware/error_handler.js
> +module.exports = function AppError(message, httpStatus = 404) {
AppError looks really meaningless and httpStatus = 404 assuming httpStatus as 404 is wrong. 

In error_middleware, 

Add various files  like,
internal-server-error.js - default HTTP  code - 500
not-found-error.js -  default HTTP  code - 404
conflict-error.js  - default HTTP  code - 409

2021-05-19 06:55 UTC, impiyush83 requested changes
Add error handlers which align to HTTP error codes

2021-05-19 13:57 UTC, palisadoes commented
Closing this pull request due to a lack of response from the original author.

2021-05-19 13:57 UTC, closed without merging