Made the session optional for database with  replica set not configured.
PalisadoesFoundation/talawa-api pull request #1836
Opened 2024-02-11 17:12 UTC by adi790uu

**What kind of change does this PR introduce?**

bugfix

**Issue Number:**

Fixes #1772 

**Did you add tests for your changes?**

Yes

**Snapshots/Videos:**

https://github.com/PalisadoesFoundation/talawa-api/assets/132701661/726039a8-72d9-4afc-9e4f-72a9aced1700

![Screenshot 2024-02-11 at 10 39 15 PM](https://github.com/PalisadoesFoundation/talawa-api/assets/132701661/19163525-c662-47a6-8486-6a5a5d7b63db)

**If relevant, did you update the documentation?**

No

**Summary**

Made the session optional for local database which does not have replica set enabled.

**Does this PR introduce a breaking change?**

No

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

Yes

2024-02-11 17:29 UTC, palisadoes commented
This solution only works with `mongodb.net`

1. How can you make this universally applicable?
2. How can we also fix this with `setup.ts`?

2024-02-11 17:32 UTC, palisadoes commented
@EshaanAgg, @varshith257, @meetulr

1. You all had opinions on the approach. Please take a look here. My concern is that this solution isn't universally applicable as it checks or the `mongodb.net` domain.
2. It would seem that we'd need to do some connectivity test to be certain, and possibly have modifications to `setup.ts`

2024-02-11 18:08 UTC, meetulr commented
I was just thinking of running the [`hello`](https://www.mongodb.com/docs/v4.4/reference/command/hello/#:~:text=MongoDB%20drivers%20and%20clients%20use%20hello%20to%20determine,following%20form%3A%20db.%20runCommand%20%28%7B%20hello%3A%201%20%7D%29) command.

It returns information about the instance. We can check if it has properties that only a replica set would have (like hosts or setName), and start a session if it does.

2024-02-11 18:19 UTC, adi790uu commented
> I was just thinking of running the [`hello`](https://www.mongodb.com/docs/v4.4/reference/command/hello/#:~:text=MongoDB%20drivers%20and%20clients%20use%20hello%20to%20determine,following%20form%3A%20db.%20runCommand%20%28%7B%20hello%3A%201%20%7D%29) command.
> 
> It returns information about the instance. We can check if it has properties that only a replica set would have (like hosts or setName), and start a session if it does.

Yeah this seems to be a valid approach.

2024-02-11 18:55 UTC, varshith257 commented
@palisadoes I agree with @meetulr to make the solution universally applicable, we could perform a connectivity test to check if the MongoDB instance is a replica set, instead of checking for the `mongodb.net` domain. This can be done by running the `hello` command and checking if the instance has properties that only a replica set would have, such as hosts or setName. If it does, then we can start a session.

2024-02-11 19:04 UTC, varshith257 commented
Regarding `setup.ts`, we can add a warning message to inform the user if they have provided a local MongoDB URL with retry writes enabled. However, the ultimate solution would be to make the session optional for local databases without a replica set.

2024-02-11 19:11 UTC, varshith257 commented
> @EshaanAgg, @varshith257, @meetulr
> 
> 1. You all had opinions on the approach. Please take a look here. My concern is that this solution isn't universally applicable as it checks or the `mongodb.net` domain.
> 2. It would seem that we'd need to do some connectivity test to be certain, and possibly have modifications to `setup.ts`

Regarding `setup.ts`, we can add a warning message to inform the user if they have provided a local MongoDB URL with retry writes enabled. However, the ultimate solution would be to make the session optional for local databases without a replica set.

We can implement a check for it in the `db.ts` . If the MongoDB instance is not a replica set, the session will not be initiated. This approach will ensure that we don't face any issues with local single-node standalone instances, and we can still have support for transactions in deployed versions.

2024-02-16 17:57 UTC, palisadoes commented
*NOTE* Read very carefully

1. We just merged this PR which upgraded the prettier package. 
    1. https://github.com/PalisadoesFoundation/talawa-api/pull/1840
1. It reformatted over 400 files. This will put your PR at risk of extensive merge conflicts.    
1. I suggest that before you merge your code to the latest upstream, or manually fix these merge conflicts that you:
    1. upgrade your `prettier` in your local branch to the same version
    1. run `prettier`
    
This will help to reduce the number of future merge conflicts for your PR.

2024-02-17 00:28 UTC, palisadoes commented
@adi790uu How's progress on this?

2024-02-17 05:05 UTC, adi790uu commented
@palisadoes almost done will create a PR today.

2024-02-17 08:28 UTC, adi790uu commented
hey @palisadoes I am getting es-lint errors after I merged the latest code from develop branch to the pr branch

2024-02-17 17:51 UTC, adi790uu commented
@palisadoes @Cioppolo14 any suggestions to solve above there are many linting errors so it is impossible to resolve them.

2024-02-17 18:52 UTC, varshith257 commented
> @palisadoes @Cioppolo14 any suggestions to solve above there are many linting errors so it is impossible to resolve them.
> 

You can make use of `lint:fix` command probably

2024-02-17 18:58 UTC, adi790uu commented
> > @palisadoes @Cioppolo14 any suggestions to solve above there are many linting errors so it is impossible to resolve them.
> 
> You can make use of `lint:fix` command probably

already tried that 
![Uploading Screenshot 2024-02-18 at 12.27.46 AM.png…]()

2024-02-17 19:04 UTC, palisadoes commented
> hey @palisadoes I am getting es-lint errors after I merged the latest code from develop branch to the pr branch. Maybe I have to create a new branch out of develop ,make my changes and then create a new pr for this issue to avoid this error.

Try that, but don't close this PR. Try deleting your local branch and recreating a branch with the same name from develop.  Make your changes before committing. You may have to do a force push to your origin too.

2024-02-17 19:12 UTC, adi790uu commented
@palisadoes I have not added any warning in setup.ts regarding replica set configuration should I do it but I think its not required for local development purpose.

2024-02-17 19:31 UTC, palisadoes commented
1. That should be OK.
2. @meetulr, @varshith257 Is this sufficient?

2024-02-18 04:36 UTC, meetulr commented
> 1. That should be OK.
> 2. @meetulr, @varshith257 Is this sufficient?

This is what I did... i.e. using the `hello` command.

Would be better if we added some logs & comments in here though, and check for a property that's more intuitive to understand, like `setName` (if it's a replica set, it would have a `setName`, otherwise it won't). Something like this:

![connect-function](https://github.com/PalisadoesFoundation/talawa-api/assets/55585268/d03ac418-36e3-4067-b96e-203bc47ad846)

![connect-function](https://github.com/PalisadoesFoundation/talawa-api/assets/55585268/94bd5d73-72e9-4319-9ee8-12b14a704057)
![non-replica-log](https://github.com/PalisadoesFoundation/talawa-api/assets/55585268/896e8170-07ae-47e3-82e7-791f779e1739)
![replica-set-log](https://github.com/PalisadoesFoundation/talawa-api/assets/55585268/b56d36f1-82db-4926-9442-91ce90cb20e3)

2024-02-18 04:46 UTC, adi790uu commented
> > 1. That should be OK.
> > 2. @meetulr, @varshith257 Is this sufficient?
> 
> This is what I did... i.e. using the `hello` command.
> 
> Would be better if we added some logs & comments in here. And check for a property that's more intuitive to understand, like `setName` (if it's a replica set, it would have a `setName`, otherwise it won't). Something like this:
> 
> ![connect-function](https://github.com/PalisadoesFoundation/talawa-api/assets/55585268/d03ac418-36e3-4067-b96e-203bc47ad846)
> ![checkIfReplicaSet](https://github.com/PalisadoesFoundation/talawa-api/assets/55585268/0370c1ed-d4a9-489e-857b-793fe8e3c8dd)
> 
> ![non-replica-log](https://github.com/PalisadoesFoundation/talawa-api/assets/55585268/896e8170-07ae-47e3-82e7-791f779e1739)
> ![replica-set-log](https://github.com/PalisadoesFoundation/talawa-api/assets/55585268/b56d36f1-82db-4926-9442-91ce90cb20e3)

Yeah we can do logging and in my code I am checking for hosts array if it's present then it's a replica set otherwise it's not.

2024-02-18 05:29 UTC, adi790uu commented
@palisadoes is logging required, should I implement that?

2024-02-18 14:46 UTC, varshith257 commented
> @palisadoes is logging required, should I implement that?

Go for it. It indicates info of session

2024-02-18 15:28 UTC, palisadoes commented
If the type of logging does not significantly degrade performance, and is available for the community versions of Mongo, then we should do it.

2024-02-19 16:55 UTC, adi790uu commented
@palisadoes implemented logging and I have written test as well for the script, do give your feedback if any change is still required.

2024-02-19 17:17 UTC, palisadoes commented
Have you tested this with both a local and cloud instances? We must be able to create events without issue in Talawa-Admin

2024-02-19 17:18 UTC, adi790uu commented
I have tested it locally @palisadoes

2024-02-19 17:34 UTC, palisadoes commented
1. Using the mongoDB Atlas cloud service which many of the developers seem to be using. It uses replica sets.
2. Ask one of the others in this PR's thread and that of the original issue to test against this PR too.

2024-02-19 17:54 UTC, adi790uu commented
> 1. Using the mongoDB Atlas cloud service which many of the developers seem to be using. It uses replica sets.
> 2. Ask one of the others in this PR's thread and that of the original issue to test against this PR too.

Yeah I have tested the mongdb atlas instance, I misunderstood the question.

2024-02-19 17:55 UTC, adi790uu commented
@varshith257 @meetulr can you verify/review this

2024-02-19 18:23 UTC, varshith257 requested changes
As I suggested earlier, Can you add an additional check for the 'setName' property in the replica set condition?

2024-02-19 18:25 UTC, adi790uu commented on src/db.ts
> +    if ("hosts" in result) {
Yeah we can do that, ok will add that as well.

2024-02-19 19:27 UTC, EshaanAgg submitted a review, later dismissed

2024-02-19 19:29 UTC, palisadoes commented on src/db.ts
> +    if ("hosts" in result) {
Yes, add this additional check so we can merge the PR.

2024-02-19 19:29 UTC, varshith257 approved these changes
![WhatsApp Image 2024-02-20 at 00 36 57_9e9feb7d](https://github.com/PalisadoesFoundation/talawa-api/assets/117595548/14a9e752-0e82-4c3a-a97e-471e6697ce80)

LGTM

2024-02-22 18:50 UTC, adi790uu commented
@palisadoes added the setName check as well

2024-02-23 03:43 UTC, EshaanAgg approved these changes

2024-02-23 03:51 UTC, palisadoes approved these changes

2024-02-23 03:51 UTC, merged