Potential Privilege Escalation BugFix
PalisadoesFoundation/talawa-api pull request #1839
Opened 2024-02-12 06:01 UTC by krishna619

What kind of change does this PR introduce?

BugFix

Issue Number:

Fixes https://github.com/PalisadoesFoundation/talawa-api/issues/1792

Did you add tests for your changes?

Yes.

Summary

This vulnerability could allow attackers to gain unauthorized access to user accounts, potentially leading to privilege escalation and compromise of sensitive data.
So, the token should be verified based on the original email address associated with the request.

Does this PR introduce a breaking change?
No

Other information

Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?

2024-02-12 07:35 UTC, SiddheshKukade requested changes
Fix the changes requested. Otherwise code is looking good to merge

2024-02-12 07:35 UTC, SiddheshKukade commented on README.md
No need to make changes in this file

2024-02-12 08:43 UTC, krishna619 commented on README.md
@SiddheshKukade 
on which file exactly do I have to make the change?

2024-02-13 13:03 UTC, Cioppolo14 commented
@krishna619 Please fix the failing tests.

2024-02-14 10:39 UTC, closed without merging

2024-02-14 13:09 UTC, palisadoes commented
We have a policy of unassigning contributors who close PRs without getting validation from our reviewer team. This is because:

1. We start looking for people to review PRs when you submit them. 
2. We often contact them and link to the PR. If the PR is closed the whole effort is wasted.
3. The historical thread of reviewer comments is broken when the work is spread across multiple PRs. The quality of our code is affected negatively.

Please be considerate of our volunteers' limited time and our desire to improve our code base.

This policy is stated as a pinned post in all our Talawa repositories. Our YouTube videos explain why this practice is not acceptable to our Community.