Feature:  Add Support for Event Invitees and Registrants
PalisadoesFoundation/talawa-api pull request #1858
Opened 2024-02-16 08:36 UTC by aialok

**What kind of change does this PR introduce?**

- Support added for event invitees and registrants.
- Admins can invite, register, and check-in users.
- Invited users can register for events.

**Issue Number:**

Fixes #1644 

**Did you add tests for your changes?**

- Yes

**Snapshots/Videos:**

**If relevant, did you update the documentation?**

**Summary**

- The eventAttendee model was updated.
- Required mutations and queries were added to facilitate admin actions: inviting, registering, and checking-in users.
- Invited users can register for events.
- Refactor checkIn model 

**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

2024-02-16 08:38 UTC, aialok commented
I will be fixing all the failed tests and please suggest me required changes if any.

2024-02-16 17:58 UTC, palisadoes commented
*NOTE* Read very carefully

1. We just merged this PR which upgraded the prettier package. 
    1. https://github.com/PalisadoesFoundation/talawa-api/pull/1840
1. It reformatted over 400 files. This will put your PR at risk of extensive merge conflicts.    
1. I suggest that before you merge your code to the latest upstream, or manually fix these merge conflicts that you:
    1. upgrade your `prettier` in your local branch to the same version
    1. run `prettier`
    
This will help to reduce the number of future merge conflicts for your PR.

2024-02-17 06:32 UTC, aialok commented
@palisadoes, please review this pull request as we need a series of pull requests for this in talawa-admin and talawa-mobile. Also, if there is anything extra needed to be added, please do let me know.

2024-02-18 05:36 UTC, SiddheshKukade requested changes
Kindly check the comments. Other than that PR looks good to merge. I think the fields that you've deleted may cause other apis to fail

2024-02-18 05:36 UTC, SiddheshKukade commented on schema.graphql
I wanted a clarification on why you've removed this fields

2024-02-18 05:36 UTC, SiddheshKukade commented
@aialok please take a pull from origin develop

2024-02-18 06:10 UTC, aialok commented on schema.graphql
We have already discussed the removal of these fields, as they are already being tracked elsewhere also removed fields have not been used previously, so refactoring the code is preferable if they are not being used.

For further reference:
https://github.com/PalisadoesFoundation/talawa-api/issues/1644#issuecomment-1879984882

2024-02-18 06:12 UTC, aialok commented
> Kindly check the comments. Other than that PR looks good to merge. I think the fields that you've deleted may cause other apis to fail

I will be fixing all the failing api's if any.

2024-02-19 09:45 UTC, aialok commented
@palisadoes, may I work on its frontend part until the PR gets reviewed? If I need anything extra in the frontend, then I will make the necessary changes in the backend accordingly.

2024-02-19 15:13 UTC, palisadoes approved these changes

2024-02-19 15:13 UTC, merged

2024-02-19 15:13 UTC, palisadoes commented
Go ahead. I've approved and merged this