Potential Privilege Escalation BugFix
PalisadoesFoundation/talawa-api pull request #1866
Opened 2024-02-18 17:49 UTC by krishna619

What kind of change does this PR introduce?

BugFix

Issue Number:

Fixes https://github.com/PalisadoesFoundation/talawa-api/issues/1792

Did you add tests for your changes?

Yes.

Summary

This vulnerability could allow attackers to gain unauthorized access to user accounts, potentially leading to privilege escalation and compromise of sensitive data.
So, the token should be verified based on the original email address associated with the request.

Does this PR introduce a breaking change?
No

Other information 

Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?

2024-02-18 18:09 UTC, krishna619 commented
@palisadoes @SiddheshKukade 
I have taken the latest pull and fixed the required formatting.

2024-02-18 19:04 UTC, palisadoes commented
Please get the code coverage of the patch higher to match that of the target before we assign reviewers

2024-02-18 19:35 UTC, krishna619 commented
@palisadoes fixed it

2024-02-19 02:20 UTC, Cioppolo14 commented
@xoldyckk @SiddheshKukade Can you review this PR?

2024-02-19 19:14 UTC, EshaanAgg requested changes
LGTM but needs minor changes.

2024-02-19 19:14 UTC, EshaanAgg commented on package-lock.json
Why are there changes in this file?

2024-02-19 19:14 UTC, EshaanAgg commented on tests/resolvers/Mutation/forgotPassword.spec.ts
> +/* eslint-disable @typescript-eslint/no-explicit-any */
Do not use these comments for the whole file. Try to avoid using them, and if absolutely necessary, use them for particular lines.

2024-02-20 06:13 UTC, krishna619 commented
@EshaanAgg @SiddheshKukade Please review, I have made the required changes

2024-02-22 18:40 UTC, krishna619 commented
@palisadoes  please review it

2024-02-24 20:07 UTC, krishna619 commented
@palisadoes @EshaanAgg

2024-02-27 17:16 UTC, krishna619 commented
@palisadoes any update on the review?
@EshaanAgg

2024-02-28 11:56 UTC, krishna619 commented
@palisadoes This PR was automatically closed, I accidentally forced push.
Please reopen it.

2024-02-28 11:57 UTC, krishna619 commented
This was accidentally closed

2024-03-03 15:28 UTC, palisadoes commented
@SiddheshKukade
@EshaanAgg
@DMills27

Please review

2024-03-05 18:48 UTC, krishna619 commented
> @SiddheshKukade @EshaanAgg @DMills27
> 
> Please review

Please review

2024-03-06 09:19 UTC, krishna619 commented
merged

2024-03-06 09:19 UTC, closed without merging