Fixed tests for src/setup/setImageUploadSize.ts
PalisadoesFoundation/talawa-api pull request #2034
Opened 2024-03-20 13:45 UTC by aarishshahmohsin

**What kind of change does this PR introduce?**
Fixed tests for src/setup/setImageUploadSize.ts increasing coverage.

**Issue Number:**
Fixes #1924 

**Did you add tests for your changes?**
NA

**Snapshots/Videos:**
NA

**If relevant, did you update the documentation?**
NA

**Summary**
Fixed tests for src/setup/setImageUploadSize.ts increasing coverage.

**Does this PR introduce a breaking change?**
No

**Other information**
NA

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**
Yes

2024-03-20 16:31 UTC, Olatade commented
@aarishshahmohsin can you fix the failing tests please

2024-03-20 23:55 UTC, Cioppolo14 commented
@SiddheshKukade @EshaanAgg Can you review this PR?

2024-03-22 16:50 UTC, palisadoes commented
This is an update on the PR merging freeze:

1. In the next few hours we will be merging the `develop-userTypeFix` branch into the `develop` branch. 
1. The `develop-userTypeFix` branch was created to fix a long standing design flaw where Admins were Admins of all organizations, not specific ones.
1. The `userType` field has been removed from the User collection and it has been replaced by an `appUserProfileId` field.
    1. This field is `null` if the user isn’t registered to use the apps. This will help people to add users manually during the event checkin process, or if an Admin wants to manually add someone in the Admin dashboard.
    1. When not `null` the `AppUserProfileID` will reference a `AppUserProfile` collection with App related information such as the organizations for which a user may be an Admin.
    1. The updated schema can be found here https://github.com/PalisadoesFoundation/talawa-api/blob/develop-userTypeFix/schema.graphql
    1. This is the parent issue that we have been using to track progress:
        1. https://github.com/PalisadoesFoundation/talawa-api/issues/1965
1. This merge will cause some conflicts in your PR.

We decided to do this at the beginning of the weekend to give us all time to adjust PR code and create bug fixes that may arise.

Update your code at or after midnight GMT on the morning of March 23, 2024. (5:30am IST). 

If your PRs have already been approved, request a re-review after fixing the conflicts and refactoring to the new `AppUserProfileID` methodology.

2024-03-23 15:46 UTC, palisadoes commented
## The PR merging freeze is lifted.

1. We are working on bug fixes that may arise. These should be few and are being tracked here:
    1. https://github.com/orgs/PalisadoesFoundation/projects/24
1. Please update your PRs and local repos. Fix any new merge conflicts that may have occurred.
    
Background:

1. The `develop-userTypeFix` branch was created to fix a long standing design flaw where Admins were Admins of all organizations, not specific ones.
1. The `userType` field has been removed from the User collection and it has been replaced by an `appUserProfileId` field.
    1. This field is `null` if the user isn’t registered to use the apps. This will help people to add users manually during the event checkin process, or if an Admin wants to manually add someone in the Admin dashboard.
    1. When not `null` the `AppUserProfileID` will reference a `AppUserProfile` collection with App related information such as the organizations for which a user may be an Admin.
    1. The updated schema can be found here https://github.com/PalisadoesFoundation/talawa-api/blob/develop-userTypeFix/schema.graphql
    1. This is the parent issue that we have been using to track progress:
        1. https://github.com/PalisadoesFoundation/talawa-api/issues/1965
1. If your PRs have already been approved, request a re-review after fixing the conflicts and refactoring to the new `AppUserProfileID` methodology.

2024-03-23 15:47 UTC, palisadoes commented
## The PR merging freeze is lifted.

1. We are working on bug fixes that may arise. These should be few and are being tracked here:
    1. https://github.com/orgs/PalisadoesFoundation/projects/24
1. Please update your PRs and local repos. Fix any new merge conflicts that may have occurred.
    
Background:

1. The `develop-userTypeFix` branch was created to fix a long standing design flaw where Admins were Admins of all organizations, not specific ones.
1. The `userType` field has been removed from the User collection and it has been replaced by an `appUserProfileId` field.
    1. This field is `null` if the user isn’t registered to use the apps. This will help people to add users manually during the event checkin process, or if an Admin wants to manually add someone in the Admin dashboard.
    1. When not `null` the `AppUserProfileID` will reference a `AppUserProfile` collection with App related information such as the organizations for which a user may be an Admin.
    1. The updated schema can be found here https://github.com/PalisadoesFoundation/talawa-api/blob/develop-userTypeFix/schema.graphql
    1. This is the parent issue that we have been using to track progress:
        1. https://github.com/PalisadoesFoundation/talawa-api/issues/1965
1. If your PRs have already been approved, request a re-review after fixing the conflicts and refactoring to the new `AppUserProfileID` methodology.

2024-03-23 18:47 UTC, palisadoes commented on tests/setup/setImageUploadSize.spec.ts
> -  Test Case 1:
Why have you removed these clarifying comments?

2024-03-23 18:48 UTC, palisadoes requested changes
See comments

2024-03-23 18:48 UTC, palisadoes commented on tests/setup/setImageUploadSize.spec.ts
> -  Description: setImageUploadSize truncates size if exceeding the maximum limit.
Why have you removed these clarifying comments?

2024-03-23 18:48 UTC, palisadoes commented on tests/setup/setImageUploadSize.spec.ts
> -  Description: The validateImageFileSize function returns true for a size within the valid range.
Why have you removed these clarifying comments?

2024-03-23 18:48 UTC, palisadoes commented on tests/setup/setImageUploadSize.spec.ts
> -  Description: setImageUploadSize updates .env_test for the test environment with the correct size.
Why have you removed these clarifying comments?

2024-03-23 18:48 UTC, palisadoes commented on tests/setup/setImageUploadSize.spec.ts
> -  Description: The validateImageFileSize function returns false for a size exceeding the valid range.
Why have you removed these clarifying comments?

2024-03-24 12:17 UTC, Cioppolo14 commented
@aarishshahmohsin Please fix the failed tests.

2024-03-25 09:12 UTC, aarishshahmohsin commented
@Cioppolo14 @SiddheshKukade @EshaanAgg @palisadoes I am not able to replicate the test error locally. My tests are passing locally.

2024-03-29 10:40 UTC, aarishshahmohsin commented
@palisadoes please review this PR.

2024-03-29 12:13 UTC, palisadoes commented
You didn't answer my questions in the previous review. You marked then as resolved without a response

2024-03-29 16:42 UTC, aarishshahmohsin commented
> You didn't answer my questions in the previous review. You marked then as resolved without a response

I added those comments.

2024-03-30 22:09 UTC, aarishshahmohsin commented
@palisadoes Please review this PR. I am not able to work on other issues.

2024-03-30 22:13 UTC, palisadoes approved these changes

2024-03-30 22:13 UTC, merged