Remove `allotedSeat` and `allotedRoom` from Checkin
PalisadoesFoundation/talawa-api pull request #2164
Opened 2024-04-06 10:57 UTC by lakshz

**What kind of change does this PR introduce?**
This PR removes any instance of `allotedRoom` and `allotedSeat` in the codebase

**Issue Number:**

Fixes #2002 

**Did you add tests for your changes?**
Y

**Snapshots/Videos:**
N/A

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

2024-04-06 13:51 UTC, palisadoes requested changes
See comments

2024-04-06 13:51 UTC, palisadoes commented on .github/workflows/pull-request.yml
> +        run: echo "${{ env.CHANGED_FILES }}"
Revert all changes to this file. It is out of scope of the PR

2024-04-06 13:56 UTC, lakshz commented
@palisadoes Lint tests were failing due to an error. I'm trying to resolve that error, the reason I echoed changed-files in the workflow

2024-04-06 14:17 UTC, lakshz commented
![Uploading Screenshot 2024-04-06 at 19.46.52.png…]()
I see something is wrong with the `changed-files` actions. It is returning wrong files changed in the PR.

Let me work on fixing this.

2024-04-06 14:26 UTC, lakshz commented
Fixed after updating the version for `tj-actions/changed-files`.  Probably, the error was resolved in v44 recently:

<img width="1272" alt="Screenshot 2024-04-06 at 19 55 28" src="https://github.com/PalisadoesFoundation/talawa-api/assets/81241551/94478d85-f5c1-4361-b722-5323dcc57c31">

2024-04-06 17:15 UTC, palisadoes requested changes
Revert all changes to `pull-request.yml` 

It is out of scope of the issue

2024-04-06 22:00 UTC, lakshz commented
@palisadoes Changes to `pull-request.yml` were done to make the tests pass.

2024-04-07 22:23 UTC, palisadoes approved these changes

2024-04-07 22:23 UTC, merged