feat: Enhance authorization rules for createPost and updatePost mutations
PalisadoesFoundation/talawa-api pull request #2225
Opened 2024-04-18 00:59 UTC by akhilender-bongirwar

**What kind of change does this PR introduce?**
This PR enhances the authorization rules for createPost and updatePost mutations.

**Issue Number:**

Fixes #2202 

**Did you add tests for your changes?**
Yes

**Snapshots/Videos:**

**If relevant, did you update the documentation?**
N/A

**Summary**

- Expanded authorization rules for createPost mutation to include superadmins, allowing them to create posts regardless of organization membership.
- Granted permissions to both superadmins and organization admins for updatePost mutation, enabling them to update posts associated with their respective organizations.
- Ensured user cache is also implemented.
- Covered code with tests and ensured no other functionality got affected.

**Does this PR introduce a breaking change?**
No

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**
Yes

2024-04-18 08:09 UTC, Huy1996 commented
@EshaanAgg @DMills27 Could you review this PR?

2024-04-18 13:20 UTC, palisadoes requested changes
How are Admins handled? I see you have made updates for SuperAdmins.

2024-04-18 18:55 UTC, akhilender-bongirwar commented
Sir PTAL

2024-04-21 07:02 UTC, palisadoes approved these changes

2024-04-21 07:02 UTC, merged