added payment gateway stripe
PalisadoesFoundation/talawa-api pull request #224
Opened 2021-04-11 11:29 UTC by yasharth291

What kind of change does this PR introduce?
It is an Enhancement

Summary

Adding payment gateway to take the donation from the user motivated me to raise this PR.

Other information
Fixes #211

Use this link to get to know about the stripe.js https://stripe.com/docs/js/

Changes I have done

Added the Stripe.js Payment gateway.
Inserted the Webhook for the notification and checking the endpoint
The webhooks can be saved in the mongo db or a mail for the same can be sent to the admin
Added the middleware to check the response before the payment is made so the user do not use it for spamming
Adding 3D checking model and SCA security
Adding a subscription model for the recurring payments
Creating the invoices and sending them to user of recurring payments

2021-04-11 11:29 UTC, yasharth291 commented
@Laurell876  sir i have rebased

2021-04-28 15:29 UTC, palisadoes commented
@DMills27 @Laurell876 please review

2021-04-28 15:50 UTC, yasharth291 commented
@palisadoes  sir this is gsoc parallel issue

2021-05-17 15:15 UTC, yasharth291 commented
@palisadoes  sir could you please review it sir

2021-05-19 06:48 UTC, impiyush83 requested changes
@yasharth291  Have added comments for code cleanup

2021-05-19 06:48 UTC, impiyush83 commented on resolvers/Payment_Gateway/checkout.js
> +	[
Pull the schema validation in some reusable middleware function

2021-05-19 06:48 UTC, impiyush83 commented on resolvers/Payment_Gateway/checkout.js
> +		let {amount, id} = req.body //here amount is the amount for donation, and id is the way the user is going to pay like card UPI and other methods
use const as you are not modifying the variables

2021-05-19 06:48 UTC, impiyush83 commented on resolvers/Payment_Gateway/checkout.js
> +	require('dotenv').config({ path: './.env' });
checking env variables available or not is not required

2021-05-19 06:48 UTC, impiyush83 commented on resolvers/Payment_Gateway/checkout.js
> +	const stripe = require('stripe')(process.env.STRIPE_SECRET_KEY);
const { STRIPE_SECRET_KEY } = require('config');

2021-05-19 06:48 UTC, impiyush83 commented on resolvers/Payment_Gateway/checkout.js
> +	const stripe = require('stripe')(process.env.STRIPE_SECRET_KEY);
Config file must have all mappings of env vars: 

module.exports = { 
    STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY
};

2021-05-19 06:48 UTC, impiyush83 commented on resolvers/Payment_Gateway/checkout.js
> +	  const domainURL = process.env.DOMAIN;
pull DOMAIN out in config file as mentioned above

2021-05-19 06:48 UTC, impiyush83 commented on resolvers/Payment_Gateway/checkout.js
> +	  const pmTypes = (process.env.PAYMENT_METHOD_TYPES || 'card').split(',').map((m) => m.trim());
pull this env variable in config file

2021-05-19 06:48 UTC, impiyush83 commented on resolvers/Payment_Gateway/checkout.js
> +		mode: 'payment',
payment is a constant pull that in constants file

2021-05-19 06:48 UTC, impiyush83 commented on resolvers/Payment_Gateway/checkout.js
> +		let event;
use const whereever possible.

2021-05-19 06:48 UTC, impiyush83 commented on resolvers/Payment_Gateway/subscription.js
> +    if (process.env.STRIPE_WEBHOOK_SECRET) {
pull this out in a separate function which spits out data and eventType,  at last assign those variables to data and eventType declaring as const

2021-05-19 06:48 UTC, impiyush83 commented on resolvers/Payment_Gateway/subscription.js
> +    if (eventType === "checkout.session.completed") {
pull out checkout.session.completed in constants folder -> eventTypes.js file

2021-05-19 06:49 UTC, closed without merging