bug issue#223 resolved
PalisadoesFoundation/talawa-api pull request #240
Opened 2021-05-17 07:26 UTC by ssaumyaa7

**What kind of change does this PR introduce?**
-bugfix 

**Summary**
-There was bug while comparing, string and int cannot be === as there needs to be the same datatype but when we use == the datatypes are ignored rather the conent is compared.

**Other information**
issue no. #223

2021-05-19 06:57 UTC, impiyush83 commented on resolvers/functions/creatorCheck.js
>    if (!isCreator) {
== is loosely check. which is a bad practice
use === ,  match types of the variables

2021-05-19 06:58 UTC, impiyush83 requested changes
Use === instead of ==, by checking datatypes

2021-05-19 07:07 UTC, ssaumyaa7 commented
@impiyush83 taking your point in consideration I'll make the necessary changes again.... Thankyou

2021-05-19 11:51 UTC, ssaumyaa7 commented
@impiyush83 @palisadoes Rather than using == while comparing, converted type to string

2021-05-19 12:05 UTC, impiyush83 approved these changes

2021-05-19 13:53 UTC, palisadoes commented
@ssaumyaa7  @impiyush83 Let's have more meaningful pull requests. For example using `===` consistently in all dart files would be a more useful, and require less interruptions for approvals. Please consider the time of the reviewers.

2021-05-19 13:53 UTC, merged

2021-06-18 06:27 UTC, ssaumyaa7 commented
@ranilwallace sir, @DMills27 sir, 
Please review, even after getting this merged. This is not reviewed hence not reflects my name in the contribution