bug fix : events can be removed by event admins or org admins only
PalisadoesFoundation/talawa-api pull request #271
Opened 2021-05-25 09:37 UTC by akshatgarg12

**What kind of change does this PR introduce?**
bugfix : events can now be only removed by the the event admins and organisation admins

**Did you add tests for your changes?**
Yes, tested on graphiql interface

**If relevant, did you update the documentation?**

**Summary**

#261 Solves a security bug ,prevents user from deleting events they didn't create.

**Does this PR introduce a breaking change?**
nope

**Other information**
I had to use the .toString() method to compare the objectIds as some were present in type string and some in ObjectId

2021-05-29 22:05 UTC, sumitra19jha commented on resolvers/event_mutations/removeEvent.js
> +  const isUserOrganisationAdmin =
Use `includes()`

2021-05-29 22:05 UTC, sumitra19jha commented on resolvers/event_mutations/removeEvent.js
> +  const isUserEventAdmin =
Use `includes()`

2021-05-29 23:48 UTC, palisadoes requested changes
Please fix the conflict in the file: `resolvers/event_mutations/removeEvent.js`

2021-05-30 10:47 UTC, akshatgarg12 commented
@palisadoes @sumitra19jha done!

2021-05-30 10:52 UTC, impiyush83 requested changes
@akshatgarg12   Update your master with latest master.

2021-05-30 10:52 UTC, impiyush83 commented on resolvers/event_mutations/removeEvent.js
>    if (!event) throw new Error('Event not found');
Use standardized error classes

2021-05-30 10:52 UTC, impiyush83 commented on resolvers/event_mutations/removeEvent.js
> +    throw new Error("Non-Admin User cannot delete event they didn't create");
Use standardized error classes

2021-05-30 11:06 UTC, akshatgarg12 commented on resolvers/event_mutations/removeEvent.js
>    if (!event) throw new Error('Event not found');
@impiyush83  yes done

2021-05-30 11:08 UTC, palisadoes commented
@DMills27
@xsh2047
@Laurell876 

Please review and merge

2021-05-30 11:19 UTC, impiyush83 approved these changes

2021-05-30 11:47 UTC, sumitra19jha approved these changes

2021-05-31 21:50 UTC, ranilwallace commented
Please resolve all conversations so we can merge.

2021-05-31 21:50 UTC, ranilwallace approved these changes

2021-06-01 00:36 UTC, palisadoes approved these changes

2021-06-01 00:38 UTC, palisadoes approved these changes

2021-06-01 00:40 UTC, palisadoes commented
@akshatgarg12  you need to resolve the comments from @sumitra19jha before this can be merged.

2021-06-01 01:01 UTC, palisadoes approved these changes

2021-06-01 05:18 UTC, akshatgarg12 commented
> @akshatgarg12 [you need to resolve the comments](https://github.com/PalisadoesFoundation/talawa-api/pull/271/files/6ce45ab0bb9a831a40f9f0eb60b24b00dc2dc7ac#r641988882) from @sumitra19jha before this can be merged.

done.

2021-06-01 05:25 UTC, merged