Feature Request : Add Talawa-API to run as systemd in Linux (All suggestion are taken from codeRabbit AI after resolving those new clean PR )
PalisadoesFoundation/talawa-api pull request #2809
Opened 2024-12-30 20:22 UTC by PurnenduMIshra129th

**What kind of change does this PR introduce?**

Feature

**Issue Number:**

Fixes #2754 

**Did you add tests for your changes?**

No

**Snapshots/Videos:**

https://github.com/user-attachments/assets/30124df5-f44b-4c09-b22d-e0c23c296eff

If relevant, did you update the documentation?

Yes I added document named installation.md on /example/linux/

Summary
Running the Talawa API service as a system daemon using systemd offers numerous benefits, including automatic startup and restart, centralized management, and dependency handling. It enhances security by running the service as a specific user and group, and improves reliability by automatically restarting the service if it crashes. Systemd provides centralized logging and monitoring, making it easier to diagnose issues. It also ensures consistent service states and resource management, preventing resource exhaustion. Overall, using systemd simplifies service management, enhances security, and ensures high availability and reliability of the Talawa API service.

Does this PR introduce a breaking change?
No

Other information
running the Talawa API service as a system daemon using systemd, highlighting the improvements in reliability, security, and manageability.Dynamically starts the development and production server on .env file configuration.Easily Log files are avaliable we don't have to go deeper in the file configuration It is under the /example/linux/talawa.api.log Every detailed error u can see here.

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

Yes

2024-12-30 20:50 UTC, PurnenduMIshra129th commented on example/linux/systemd/Talawa-api.sh
> +
resolved changed

2024-12-30 21:08 UTC, PurnenduMIshra129th commented on example/linux/systemd/Talawa-api.sh
> +PROD_PATH="dist/index.js"
absolute path is best

2024-12-30 21:09 UTC, PurnenduMIshra129th commented on example/linux/systemd/Talawa-api.sh
> +fi
not required as it is a manual verification by user in the process of installation

2024-12-30 21:09 UTC, PurnenduMIshra129th commented on example/linux/systemd/Talawa-api.sh
> +fi
already verified this permission

2024-12-30 21:12 UTC, PurnenduMIshra129th commented on example/linux/installation.md
> +
not required as env file it self make the file secure also node env we get is already verified

2024-12-30 21:17 UTC, PurnenduMIshra129th commented
@palisadoes all changes i have made for this pr . Takes the best suggestion from the coderabbit to make the code better , more readable . Review once .

2025-01-01 21:06 UTC, PurnenduMIshra129th commented
@palisadoes plz review this pr . If necessary to change some then give suggestion. For the above conflicts file of graphql these are auto generated .If it will remain unmerge for some days then again and i have to update the branch solve coflicts, also resolve the conversation of codeRabbit .

2025-01-01 22:50 UTC, palisadoes commented
Please fix the conflicting files and I'll review

2025-01-01 22:57 UTC, palisadoes requested changes
See comments

2025-01-01 22:57 UTC, palisadoes commented on example/linux/systemd/talawa-api.service
> +# Description of the service
1. Rearrange the file to have a top section that the user edits and a bottom section that they don't have to, like this:
    1. https://github.com/PalisadoesFoundation/switchmap-ng/blob/main/examples/linux/systemd/switchmap_dashboard.service
1. Keep the comments above each line. They are useful
2. Use environment variables to reduce the amount of edits the user requires. The example above does that.
3. Add a runtime directory
4. Evaluate whether you need to add any of the parameters in the example above
5. Add a README section at the top like in the example
6. Here is a better layout
    ![image](https://github.com/user-attachments/assets/14a67c21-6b34-4faa-8e37-195ad697d23a)

2025-01-02 19:36 UTC, PurnenduMIshra129th commented on example/linux/systemd/talawa-api.service
> +# Description of the service
done changes

2025-01-02 20:51 UTC, PurnenduMIshra129th commented
@palisadoes plz review . makes the necessary changes you suggest and solved the conflicts

2025-01-03 00:00 UTC, Cioppolo14 commented
There isn’t an issue assigned to you for this PR. Please follow the guidelines in our PR_GUIDELINES.md file. We have the procedures in place so that everyone has a fair chance of contributing. I will be closing this pull request. Please follow the procedures and resubmit when ready.

2025-01-03 03:41 UTC, palisadoes commented
Reopening. There was a typo in the issue #

2025-01-03 03:50 UTC, palisadoes approved these changes

2025-01-03 03:50 UTC, palisadoes commented on example/linux/systemd/talawa-api.service
> +# Description of the service
1. The comment blocks were done, but you haven't put the user configurable variables above. The user may not want to run as `talawa` for example
2. CODEROOT should be `/path/to/your/talawa-api/` for example. The the variable can be used later on as explained in the comments below.
1. The idea is that the user must be completely guided.  Add the text at the top exactly, with the appropriate updates. It is much clearer than what you have. The user shouldn't have to refer to INSTALLATION.md to have a perfect experience.

    ![image](https://github.com/user-attachments/assets/4d3b6513-4c9e-4f1b-8e6c-51f984648981)

2025-01-03 03:50 UTC, palisadoes commented on example/linux/systemd/talawa-api.service
> +ExecStart=/path/to/your/talawa-api/example/linux/systemd/Talawa-api.sh
Update to reflect $CODEROOT like in the link in my previous comment

2025-01-03 03:50 UTC, palisadoes commented on example/linux/systemd/talawa-api.service
> +WorkingDirectory=/path/to/your/talawa-api
Update to reflect $CODEROOT like in the link in my previous comment

2025-01-03 03:50 UTC, palisadoes commented on example/linux/systemd/talawa-api.service
> +User=talawa
Move to the top

2025-01-03 03:50 UTC, palisadoes commented on example/linux/systemd/talawa-api.service
> +RuntimeDirectory=talawa-api
Will this value always be true? If not, it should be a variable at the top

2025-01-03 03:50 UTC, palisadoes requested changes
See comments

2025-01-03 21:49 UTC, PurnenduMIshra129th commented on example/linux/systemd/talawa-api.service
> +ExecStart=/path/to/your/talawa-api/example/linux/systemd/Talawa-api.sh
updated by your suggestion . but in my case in the ExecStart it did not resolved the path . So i used absoulte path before. i am using wsl maybe due to this.

2025-01-03 21:49 UTC, PurnenduMIshra129th commented on example/linux/systemd/talawa-api.service
> +User=talawa
updated .

2025-01-03 21:50 UTC, PurnenduMIshra129th commented on example/linux/systemd/talawa-api.service
> +RuntimeDirectory=talawa-api
Runtime directory is not fixed . You can give any name. updated this one and moved to top section.

2025-01-03 21:53 UTC, PurnenduMIshra129th commented on example/linux/systemd/talawa-api.service
> +WorkingDirectory=/path/to/your/talawa-api
updated . but in my case during execStart it didnot worked properly. so i have used absolute path.

2025-01-03 21:54 UTC, PurnenduMIshra129th commented on example/linux/systemd/talawa-api.service
> +
it is working fine.

2025-01-03 21:55 UTC, PurnenduMIshra129th commented on example/linux/systemd/talawa-api.service
> +ExecStart=$CODEROOT/example/linux/systemd/Talawa-api.sh
lets see may be in other linux enviroment it may work

2025-01-03 21:55 UTC, PurnenduMIshra129th commented on example/linux/installation.md
> +- Create the log file if it does not exist:
it will coverd during installation process.

2025-01-03 21:56 UTC, PurnenduMIshra129th commented on example/linux/systemd/Talawa-api.sh
> +fi
it is user perspective . He have to read the installation guide properly because it is user's manuall installation.

2025-01-03 21:59 UTC, PurnenduMIshra129th commented on example/linux/systemd/talawa-api.service
> +# Description of the service
done these changes

2025-01-03 22:02 UTC, PurnenduMIshra129th commented
@palisadoes  done changes you have said . But using the enviroment in my case did not worked properly. If any user face this issue it is better use absoulte path. In my case i am using wsl2 . May in other linux system it may work . see these changes and tell if further any changes need to be done.

2025-01-06 10:22 UTC, PurnenduMIshra129th commented
@palisadoes if any further changes required plz check

2025-01-06 20:20 UTC, PurnenduMIshra129th commented
Any suggestion for this pr to merge?

2025-01-09 05:11 UTC, palisadoes commented
@coderabbitai full review

2025-01-10 06:19 UTC, PurnenduMIshra129th commented on schema.graphql
> +}
auto generated

2025-01-10 23:15 UTC, palisadoes commented
@coderabbitai full review

2025-01-10 23:15 UTC, palisadoes commented
I'll look at this in detail later today

2025-01-11 22:09 UTC, PurnenduMIshra129th commented on example/linux/installation.md
> +- **Node.js** (version specified in your Talawa API's `package.json`)
done

2025-01-11 22:09 UTC, PurnenduMIshra129th commented on example/linux/installation.md
> +- Proper file permissions on `/path/to/your/talawa-api`
done

2025-01-11 22:09 UTC, PurnenduMIshra129th commented on example/linux/installation.md
> +```
done

2025-01-11 22:14 UTC, PurnenduMIshra129th commented on .env_test
> +REFRESH_TOKEN_SECRET=5de257b9fa136179e07ea0d3e0d37f1c5d764a82eb1d4a640ce752b8b37d7d2a
not mine auto taken during latest pull

2025-01-11 22:15 UTC, PurnenduMIshra129th commented on example/linux/installation.md
> +```
these all verification steps are already present in script no need to write in installation.md

2025-01-11 22:16 UTC, PurnenduMIshra129th commented on .env_test
> +SMTP_SSL_TLS=
not mine auto generated during latest pull

2025-01-11 22:17 UTC, PurnenduMIshra129th commented on example/linux/installation.md
> +```
if any neccssary permission we will remove from this file then it may not work so it is better to keep as it is.

2025-01-14 15:47 UTC, palisadoes requested changes
Please merge with the latest upstream. We had to update the `.gitignore` file based on some of the sensitive data you uploaded in this PR.

Please exclude this file from the PR. It's not required for the issue.
- `schema.graphql`

2025-01-14 15:50 UTC, PurnenduMIshra129th commented
@palisadoes ok

2025-01-14 18:30 UTC, PurnenduMIshra129th commented
@palisadoes i am facing issue with conflicts don't know what to do

2025-01-14 19:38 UTC, PurnenduMIshra129th commented on data/.minio.sys/format.json
> +{"version":"1","format":"xl-single","id":"893a4950-2c9f-4915-9d4e-bd90c4cd840e","xl":{"version":"3","this":"776fcaee-89a1-4336-b54b-65f914c0889e","sets":[["776fcaee-89a1-4336-b54b-65f914c0889e"]],"di
not mine

2025-01-14 19:38 UTC, PurnenduMIshra129th commented on schema.graphql
> +}
not mine

2025-01-14 19:43 UTC, PurnenduMIshra129th commented
@palisadoes see once updated the code with latest upstream .see once if i done it perfectly or not i became confuse during this .

2025-01-16 20:24 UTC, PurnenduMIshra129th commented
@palisadoes will i have to do some changes in here or or i have to make a new pr with latest upstream ? do i make mess here what i have to do next ? is there any code i have to change or modify?

2025-01-16 21:39 UTC, palisadoes commented
1. This has to be closed. Please try again.
2. There are too many extraneous files that should not have been submitted.
3. Please merge with the latest upstream and try again

2025-01-16 21:39 UTC, closed without merging

2025-01-17 19:56 UTC, PurnenduMIshra129th commented
4_generate_graphql_sdl_file:
      run: |
        set -e
        pnpm generate_graphql_sdl_file
        git add ./schema.graphql   in this hook it autometiically adds the  ./schema.graphql  in our merge commit so we can't exclude it  or else we have to comment it.  @palisadoes  it is in lefthook.yaml

2025-01-17 20:35 UTC, palisadoes commented
You submitted 22 files when only 2-3 were required. Please resubmit