Fixes #275: Changed comparison operator
PalisadoesFoundation/talawa-api pull request #383
Opened 2021-11-24 03:59 UTC by uzair-ali10

**What kind of change does this PR introduce?**

Bug Fix

**Issue Number:**

Fixes #275 

**Did you add tests for your changes?**
No

**Snapshots/Videos:**
NA

**If relevant, did you update the documentation?**

NA

**Summary**

comparison between user ID from the MongoDB document and `args.data.organizationId` with ===  is invalid, however we are supposed to use `.equals()` for this

**Does this PR introduce a breaking change?**

No
**Other information**

NA

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

Yes

2021-11-26 17:30 UTC, palisadoes requested changes
@uzair-ali10 Have you checked all the code for this? I have found 185 cases where `===` is used. 

The work done to correct this in this PR seems trivial. Please let us know how you plan to proceed.

2021-12-10 15:58 UTC, sumitra19jha commented
@uzair-ali10 Let's be very consistent in our entire code base. Can you please perform changes in other API's as well

2021-12-10 16:00 UTC, uzair-ali10 commented
> 185

U want me to change all 185 instances?

2021-12-10 16:01 UTC, uzair-ali10 commented
> @uzair-ali10 Let's be very consistent in our entire code base. Can you please perform changes in other API's as well

U want me to change all 185 instances?

2021-12-10 16:15 UTC, sumitra19jha commented
> > @uzair-ali10 Let's be very consistent in our entire code base. Can you please perform changes in other API's as well
> 
> U want me to change all 185 instances?

That will be best as the entire codebase will be consistent. Later on, we can add a rule in YAML file to avoid this in upcoming PRs

2021-12-10 16:17 UTC, uzair-ali10 commented
> > > @uzair-ali10 Let's be very consistent in our entire code base. Can you please perform changes in other API's as well
> > 
> > 
> > U want me to change all 185 instances?
> 
> That will be best as the entire codebase will be consistent. Later on, we can add a rule in YAML file to avoid this in upcoming PRs

Okay, I'll do that and it should be done in a single PR, or should be broken its multiple PRs?

2021-12-10 17:02 UTC, sumitra19jha commented
> > > > @uzair-ali10 Let's be very consistent in our entire code base. Can you please perform changes in other API's as well
> > > 
> > > 
> > > U want me to change all 185 instances?
> > 
> > 
> > That will be best as the entire codebase will be consistent. Later on, we can add a rule in YAML file to avoid this in upcoming PRs
> 
> Okay, I'll do that and it should be done in a single PR, or should be broken its multiple PRs?

Single PR is fine

2021-12-26 03:25 UTC, palisadoes commented
@uzair-ali10 Are you still working on this?

2021-12-26 03:29 UTC, uzair-ali10 commented
> @uzair-ali10 Are you still working on this?

I'm really sorry, currently caught with lots of university and internship work. If anyone else would like to work on this one please assign it to them.

2021-12-26 03:43 UTC, closed without merging