Add test for updateLanguage mutation
PalisadoesFoundation/talawa-api pull request #396
Opened 2021-12-14 14:11 UTC by Prathamesh010

**What kind of change does this PR introduce?**
Adds tests for updateLanguage Mutation.

**Issue Number:**
Fixes #365 

**Does this PR introduce a breaking change?**
No.

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**
Yes.

2021-12-14 16:19 UTC, palisadoes commented
@Prathamesh010  The code base has been updated with a more recent pull request that should have fixed the issue. Please merge your branch with the lastest `upstream/develop` and push to your repo. GitHub should detect the changes and re-run the tests on the updated code.

2021-12-14 17:09 UTC, palisadoes commented
@Prathamesh010 All tests passed! Let's wait on the review from @sumitra19jha

2021-12-18 13:56 UTC, sumitra19jha requested changes

2021-12-18 13:56 UTC, sumitra19jha commented on tests/language.spec.js
> +                updateLanguage(languageCode: "es") {
Please create an array variable containing language code, then from that array randomly select one language code and use that variable as an input here

2021-12-19 09:05 UTC, sumitra19jha reviewed
Looks good now. Please add a snapshot where this test code is passing in the current repo

2021-12-19 09:24 UTC, Prathamesh010 commented
![image](https://user-images.githubusercontent.com/41731424/146669945-87955efb-5812-495e-a18d-f8b582d7460e.png)

2021-12-28 08:02 UTC, sumitra19jha approved these changes

2021-12-28 13:24 UTC, palisadoes approved these changes

2021-12-28 13:24 UTC, merged