added script to check if files contain jsdoc format comments
PalisadoesFoundation/talawa-api pull request #604
Opened 2022-03-08 07:07 UTC by akshatgarg12

**What kind of change does this PR introduce?**

**Issue Number:**

Fixes #474 

**Did you add tests for your changes?**
No

**Snapshots/Videos:**
![Screenshot 2022-03-08 at 12 30 27 PM](https://user-images.githubusercontent.com/60404253/157184421-7a8d6a38-19cb-4d4e-8cef-6f9693399c06.png)

**If relevant, did you update the documentation?**

**Summary**
1. added check-jsdocs-comment.py script which checks the file content of all js files in the codebase and looks for comments based on (/** */) this format. if a comment is found, jsdocs pipeline should run to update the documentation, else not.
2. The script sets a env variable RUN_JSDOCS in the workflow file, which can be used with an if statement to check whether to run JSdocs or not.
3. Currently JSdocs pipeline is not created as it is a part of separate child issue, but the logic has been written and can be implemented over it.

**Does this PR introduce a breaking change?**

No
**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**
Yes

2022-03-08 07:12 UTC, akshatgarg12 commented
**Checking workflow files / Checking for unauthorized file changes (pull_request)** check is failing because [this .github/workflow file ](https://github.com/PalisadoesFoundation/talawa-api/blob/develop/.github/workflows/authorized-changes-detection.yml) does not allow any changes in **/.github** folder in a PR.

2022-03-08 14:51 UTC, palisadoes commented
With each PR we check to ensure that we have tests for as much of the code base as possible, this is the code coverage test. This PR would not not be applicable as your code isn't JavaScript based. This is OK.

Yes, you are right, we have checks to make sure the `.github` directory isn't updated as this is an area where most of our automation resides. This PR hopes to improve our automation, so this is acceptable.

2022-03-08 14:55 UTC, palisadoes submitted a review, later dismissed

2022-03-09 03:24 UTC, DMills27 reviewed
Can you add a more detailed comment about what the Regex is doing? For anyone reading this in the future they might be uncertain as to how exhaustive this pattern match is.

2022-03-09 05:59 UTC, akshatgarg12 commented
> Can you add a more detailed comment about what the Regex is doing? For anyone reading this in the future they might be uncertain as to how exhaustive this pattern match is.

sure

2022-03-09 12:36 UTC, palisadoes requested changes

2022-03-09 12:36 UTC, palisadoes commented on .github/workflows/check-jsdocs-comment.py
> +                myfile.write("RUN_JSDOCS=False")
Please standardize on single quotes for all strings.

2022-03-09 12:36 UTC, palisadoes commented on .github/workflows/check-jsdocs-comment.py
> +#!/usr/bin/env python3
Please add Docstrings to all your functions and also at the top of your script like [countline.py](https://github.com/PalisadoesFoundation/talawa-api/blob/develop/.github/workflows/countline.py)

This script was created to ensure that our code base has correct documentation. The script should also have good internal documentation too.

Make sure the script is pydocstring compliant

2022-03-09 12:36 UTC, palisadoes commented on .github/workflows/check-jsdocs-comment.py
> +    # list of dir to look in repo for files
Make sure the script is pylint, pycodestyle and flake8 compliant.

2022-03-10 01:58 UTC, palisadoes approved these changes

2022-03-10 02:01 UTC, palisadoes requested changes
See comments in `pull-request.yml`

2022-03-10 02:01 UTC, palisadoes commented on .github/workflows/pull-request.yml
> +    runs-on : ubuntu-latest
Make this rely on `Code-Formatter` like `Code-Coverage` below. The correct functioning of this Action will probably rely on correct formatting. So we will need to make sure the ordering is maintained.

2022-03-11 02:01 UTC, palisadoes approved these changes

2022-03-11 02:01 UTC, merged