Resolvers: Create tests for posts.js
PalisadoesFoundation/talawa-api pull request #625
Opened 2022-03-18 13:02 UTC by priyang12

**What kind of change does this PR introduce?**

**Issue Number:**

Fixes #589

**Did you add tests for your changes?**

Yes

**Snapshots/Videos:**

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**
No

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

2022-03-18 13:15 UTC, palisadoes commented
Your tests are failing. Please fix.

2022-03-18 13:22 UTC, priyang12 commented
@palisadoes looks like the latest Organisation query is failing in my workflow?

2022-03-18 13:56 UTC, palisadoes commented
Please try to fix it. The array's order seems to be sorted differently from expected. It seems simple to do.

2022-03-25 02:41 UTC, JamaicanFriedChicken commented
Can you try to get the code coverage to 100%? @priyang12

2022-03-25 07:41 UTC, priyang12 commented
@JamaicanFriedChicken hi I have added new tests for likes and comments and the coverage is 100 can please take a look at it.

2022-03-25 14:59 UTC, palisadoes commented
Please fix the failing tests:
- https://github.com/PalisadoesFoundation/talawa-api/runs/5693546529?check_suite_focus=true

2022-03-26 01:03 UTC, JamaicanFriedChicken requested changes

2022-03-26 01:03 UTC, JamaicanFriedChicken commented on tests/resolvers/post_query/posts.spec.js
> +    console.log(response[0].comments.length);
remove the console.logs() here.

2022-03-26 07:45 UTC, closed without merging