addTest/updateProject.spec.js/issue#570
PalisadoesFoundation/talawa-api pull request #645
Opened 2022-03-26 05:34 UTC by xoldyckk

**What kind of change does this PR introduce?**

Refactors updateProject.js.
Adds test file for updateProject.js

**Issue Number:**

Fixes #570

**Did you add tests for your changes?**

Yes

**Snapshots/Videos:**

![Screenshot from 2022-03-26 11-02-42](https://user-images.githubusercontent.com/82873939/160226290-e8da273e-bb13-439c-8289-0e366e6d0d30.png)

**If relevant, did you update the documentation?**

No

**Summary**

Refactored some files to throw easily mockable errors when not in production environment. Fixed a bug where comparing mongodb's objectId was implemented incorrectly. Added test file for updateProject.js increasing code coverage across talawa-api project.

**Does this PR introduce a breaking change?**

No

**Other information**

No

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

Yes

2022-03-26 16:04 UTC, palisadoes commented
Can you get the code coverage up to 100%?

2022-03-26 16:37 UTC, xoldyckk commented
> Can you get the code coverage up to 100%?

The errors thrown by default in resolvers are not mockable. When mocked they throw `i18n is not initialized, try app.use(i18n.init)` as the error message. This occurs because of the function `requestContext.translate`. This function only runs inside the context of the actual talawa-api server. That means we have to simulate an actual talawa-api server inside our tests to test it. That's why there's this refactor :- 

      process.env.NODE_ENV !== 'production'
        ? 'User not authorized'
        : requestContext.translate('user.notAuthorized')

So, that in testing environment the errors don't call requestContext.translate function. Instead they use a plain string.

And I believe that's what's causing the test coverage to not be 100%.

2022-03-26 17:00 UTC, palisadoes commented
Can we mock `requestContext.translate` in some way?

Should we consider running an API server as part of the testing regimen and mock where necessary for the rest? I've written code in the past where I had to spin up an instance of the API to properly test end to end. I realize that this may not be practical in future where running the API may consume all test resources.

2022-03-27 03:57 UTC, xoldyckk commented
> Can we mock `requestContext.translate` in some way?
> 
> Should we consider running an API server as part of the testing regimen and mock where necessary for the rest? I've written code in the past where I had to spin up an instance of the API to properly test end to end. I realize that this may not be practical in future where running the API may consume all test resources.


I personally don't have much experience with testing. I only got recently got started with it because of this project. So, my suggestions could be wrong or unreliable. But here's my take:-

In all the integration/e2e test implementations I've seen on testing backends/server, instead of just testing the route/resolver in isolation, they all run tests on the actual server. To make testing in CI runs faster, we can pass the option `--runInBand` to the test script to make it faster. Here's the source :- [https://dev.to/vantanev/make-your-jest-tests-up-to-20-faster-by-changing-a-single-setting-i36](url).

2022-03-27 05:17 UTC, ShwetKhatri2001 commented
I'm also getting the same problem of not covering the second branch ( involving requestContext.translate ) in my open PRs.
I tried to mock it by initiating i18n with the same settings we have in server file ( `index.js` ) , but didn't get expected behaviour.

But according to me here the scope of our API test case is to check if the error is delivered, not in which language it is delivered. That's why we separated

2022-03-28 02:42 UTC, palisadoes commented
@JamaicanFriedChicken @DMills27 This was the case I spoke about today. Please please give your inputs.

2022-03-29 16:34 UTC, palisadoes commented
@JamaicanFriedChicken @DMills27 Please respond here so we have a record of your recommended approach.

2022-03-29 23:29 UTC, JamaicanFriedChicken commented
@xoldyckk @ShwetKhatri2001 Thanks guys. We will be making this into a separate issue referencing this PR to investigate the cause of this. For now, we will accept the PRs as is, as it relates to i18n even if the test coverage isn't 100%.

2022-03-29 23:30 UTC, JamaicanFriedChicken commented on tests/resolvers/event_project_mutations/updateProject.spec.js
> +let testEventProject;
it's best to put these variables at the top of the file.

2022-03-29 23:31 UTC, JamaicanFriedChicken requested changes
Still need to make some slight adjustments, almost there.

2022-04-03 02:24 UTC, JamaicanFriedChicken approved these changes

2022-04-03 15:46 UTC, merged