removed hardcodded error strings
PalisadoesFoundation/talawa-api pull request #676
Opened 2022-04-13 05:22 UTC by ebrahim354

**What kind of change does this PR introduce?**
replaces hard coded error strings with constant variables.

**Issue Number:**

Fixes #675

2022-04-13 17:58 UTC, JamaicanFriedChicken reviewed
Hey @ebrahim354, the discussion around this change was to introduce a constants file to store the hardcoded values which is good. However, to actually introduce the change on a widescale in this PR can cause breaking changes elsewhere and will likely cause merge conflicts to the other participants. 

What needs to be done was just to create the constants file and to make the change related to that particular file so then we can ask other participants to make the change as well in their PRs which will introduce this change slowly to prevent breaking changes.

2022-04-13 18:17 UTC, taslangraham commented
> Hey @ebrahim354, the discussion around this change was to introduce a constants file to store the hardcoded values which is good. However, to actually introduce the change on a widescale in this PR can cause breaking changes elsewhere and will likely cause merge conflicts to the other participants.
> 
> What needs to be done was just to create the constants file and to make the change related to that particular file so then we can ask other participants to make the change as well in their PRs which will introduce this change slowly to prevent breaking changes.

@ebrahim354, I agree with what @JamaicanFriedChicken  said. Please update PR to only include the constants.js

2022-04-15 21:47 UTC, ebrahim354 commented
Sure, I will change it.

2022-04-20 02:17 UTC, ebrahim354 commented
This should be good as a start.

2022-04-20 05:21 UTC, JamaicanFriedChicken commented on lib/resolvers/functions/creatorCheck.js
>        process.env.NODE_ENV !== 'production'
hey @ebrahim354, you're almost there. You can also place the `'production'` string in the constants file as well

2022-04-20 05:22 UTC, JamaicanFriedChicken commented on lib/resolvers/organization_mutations/removeOrganization.js
>        process.env.NODE_ENV !== 'production'
this as well

2022-04-20 05:22 UTC, JamaicanFriedChicken commented on lib/resolvers/organization_mutations/removeOrganization.js
>        process.env.NODE_ENV !== 'production'
and here

2022-04-20 05:22 UTC, JamaicanFriedChicken requested changes
Almost there.

2022-04-20 13:59 UTC, ebrahim354 commented
What about these strings should I replace them as well ? 
`
  requestContext.translate('user.notAuthorized'),
      'user.notAuthorized',
      'userAuthorization'
`

2022-04-20 21:58 UTC, JamaicanFriedChicken commented
> What about these strings should I replace them as well ? `requestContext.translate('user.notAuthorized'), 'user.notAuthorized', 'userAuthorization'`

Yes, you should replace them.

2022-04-21 18:00 UTC, ebrahim354 commented
It should be working now.

2022-04-22 01:33 UTC, JamaicanFriedChicken approved these changes

2022-04-22 18:34 UTC, palisadoes approved these changes

2022-04-22 18:34 UTC, merged