[FEATURE] Check authentication for Talawa-admin added
PalisadoesFoundation/talawa-api pull request #713
Opened 2022-06-08 03:12 UTC by asmitsirohi

**What kind of change does this PR introduce?**

feature

**Did you add tests for your changes?**

Yes

**Snapshots/Videos:**

* Query
![Screenshot 2022-06-08 at 08-22-26 Playground - http __localhost 4000_graphql](https://user-images.githubusercontent.com/63240102/172522904-2db695f0-dbac-4733-adf9-29233c02fe61.png)

* User is not authenticated
  ![Screenshot 2022-06-08 at 08-22-50 Playground - http __localhost 4000_graphql](https://user-images.githubusercontent.com/63240102/172522787-c851ed92-8c32-43b1-9560-22a33a903055.png)

* User is authenticated
![Screenshot 2022-06-08 at 08-25-23 Playground - http __localhost 4000_graphql](https://user-images.githubusercontent.com/63240102/172522946-7e3bd047-2cef-4bba-b3b5-d5bd95b4afd7.png)

**If relevant, did you update the documentation?**

No

**Summary**

This Pull request is the changes in the backend regarding PalisadoesFoundation/talawa-admin#340. 
In this, a query is added in order to check the authentication in talawa-admin.

**Does this PR introduce a breaking change?**

No

**Other information**

This pull request is under GSoC'22.

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

Yes

2022-06-08 13:42 UTC, JamaicanFriedChicken requested changes

2022-06-08 15:18 UTC, asmitsirohi commented on lib/resolvers/auth_query/checkAuth.js
> +  if (!userFound) throw new Error('User not found');
Yes, there is a constant present in the constants file, I have fixed this.

2022-06-11 04:12 UTC, JamaicanFriedChicken requested changes

2022-06-11 04:12 UTC, JamaicanFriedChicken commented on tests/resolvers/auth_query/checkAuth.spec.js
> +  test('Testing is the user logged in or not', async () => {
misspelled `is` here, should be `if`

2022-06-11 10:29 UTC, yasharth291 approved these changes

2022-06-12 05:40 UTC, palisadoes commented
Please fix the failing tests.

2022-06-12 09:17 UTC, asmitsirohi commented
@palisadoes. I have fixed the failed tests.

2022-06-13 07:55 UTC, palisadoes approved these changes

2022-06-13 07:56 UTC, merged