Tests for `src/resolvers/Mutations/addUserImage`
PalisadoesFoundation/talawa-api pull request #931
Opened 2023-01-27 06:44 UTC by kb-0311

**What kind of change does this PR introduce?**

**Issue Number:**

Fixes #909 

**Did you add tests for your changes?**

Yes
**Snapshots/Videos:**

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

Yes

2023-01-27 07:17 UTC, noman2002 requested changes
Please try to get the coverage of uploadImage.ts to 100% .

2023-01-29 10:39 UTC, noman2002 commented
@kb-0311 Good work, its at 87.27% now. Get it to 100%

2023-01-29 11:49 UTC, kb-0311 commented
@noman2002 
Yep Thanks.
Now, `uploadImage` has 100% test coverage.
I will submit another PR for `deleteImage` by tomorrow.
This PR also closes #886

2023-01-29 11:53 UTC, noman2002 approved these changes

2023-01-29 12:22 UTC, palisadoes approved these changes

2023-01-29 12:22 UTC, merged